const {supa,event}=require('../../lib/messages');
const pixel=Buffer.from('R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==','base64');
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
module.exports=async(req,res)=>{
  const mode=String(req.query?.mode||'');
  const token=String(req.query?.token||'');
  if(mode==='open'){
    try{if(token){const rows=await supa(`tenant_messages?tracking_token=eq.${encodeURIComponent(token)}&select=id`);if(rows?.[0])await event(rows[0].id,'opened',{user_agent:req.headers['user-agent']||''})}}catch{}
    res.setHeader('Content-Type','image/gif');res.setHeader('Cache-Control','no-store');return res.status(200).send(pixel);
  }
  if(mode==='copy'){
    try{const rows=await supa(`tenant_messages?tracking_token=eq.${encodeURIComponent(token)}&select=id,tenant_id`);const m=rows?.[0];if(!m)return res.status(404).send('Message not found');const tenants=await supa(`tenants?id=eq.${m.tenant_id}&select=payment_reference`);const ref=String(tenants?.[0]?.payment_reference||'');res.setHeader('Content-Type','text/html; charset=utf-8');return res.status(200).send(`<!doctype html><meta name="viewport" content="width=device-width"><title>Copy payment reference</title><body style="margin:0;background:#f4f7fb;font-family:Arial,sans-serif;color:#17324f"><main style="max-width:520px;margin:60px auto;background:white;border:1px solid #dde6ef;border-radius:18px;padding:30px;box-shadow:0 18px 50px rgba(28,52,83,.08)"><div style="font-size:12px;font-weight:800;color:#1764be">MANAGERENT4U</div><h1 style="font-size:24px">Payment reference</h1><div id="ref" style="font:800 20px Consolas,monospace;white-space:nowrap;border:1px solid #d6e2ef;background:#f7faff;border-radius:12px;padding:16px;margin:18px 0">${esc(ref)}</div><button id="copy" style="border:0;border-radius:10px;background:#1768c7;color:white;padding:12px 18px;font-weight:800;cursor:pointer">⧉ Copy reference</button><span id="ok" style="margin-left:10px;color:#16814b;font-weight:700"></span><script>document.getElementById('copy').onclick=async()=>{try{await navigator.clipboard.writeText(${JSON.stringify(ref)});document.getElementById('ok').textContent='Copied ✓'}catch(e){const r=document.createRange();r.selectNode(document.getElementById('ref'));getSelection().removeAllRanges();getSelection().addRange(r);document.getElementById('ok').textContent='Selected — press Ctrl+C'}}</script></main></body>`)}catch(e){return res.status(500).send(esc(e.message||e))}
  }
  if(mode==='view'){
    try{const rows=await supa(`tenant_messages?tracking_token=eq.${encodeURIComponent(token)}&select=*`);const m=rows?.[0];if(!m)return res.status(404).send('Message not found');await event(m.id,'link_viewed',{user_agent:req.headers['user-agent']||''});const tenants=await supa(`tenants?id=eq.${m.tenant_id}&select=name`);const name=tenants?.[0]?.name||'Tenant';res.setHeader('Content-Type','text/html; charset=utf-8');return res.status(200).send(`<!doctype html><meta name="viewport" content="width=device-width"><title>${esc(m.subject)}</title><body style="margin:0;background:#f4f7fb;font-family:Arial,sans-serif;color:#17324f"><main style="max-width:680px;margin:40px auto;background:white;border:1px solid #dde6ef;border-radius:18px;padding:32px;box-shadow:0 18px 50px rgba(28,52,83,.08)"><div style="font-size:12px;font-weight:800;color:#1764be">MANAGERENT4U</div><h1 style="font-size:26px">${esc(m.subject||'Message')}</h1><p style="color:#61758d">For ${esc(name)}</p><div style="white-space:pre-wrap;line-height:1.7;font-size:15px">${esc(m.body)}</div><div style="margin-top:28px;padding-top:18px;border-top:1px solid #edf1f5;color:#8190a1;font-size:12px">This secure page records that the message link was viewed.</div></main></body>`)}catch(e){return res.status(500).send(esc(e.message||e))}
  }
  return res.status(400).json({error:'Invalid tracking mode'});
};
