
create extension if not exists pgcrypto;

create table if not exists public.contract_intakes (
  id bigint generated by default as identity primary key,
  public_token uuid not null default gen_random_uuid() unique,
  tenant_id bigint null references public.tenants(id) on delete set null,
  building_id bigint null references public.buildings(id) on delete set null,
  unit_id bigint null references public.units(id) on delete set null,
  status text not null default 'invited' check (status in ('invited','draft','submitted','assigned','contract_ready','completed','archived')),

  tenant_first_name text,
  tenant_last_name text,
  tenant_date_of_birth date,
  tenant_id_number text,
  occupant_count integer check (occupant_count is null or occupant_count > 0),
  phone text,
  email text,
  id_front_path text,
  id_back_path text,

  has_additional_tenant boolean not null default false,
  additional_tenant_first_name text,
  additional_tenant_last_name text,
  additional_tenant_date_of_birth date,
  additional_tenant_id_number text,
  additional_id_front_path text,
  additional_id_back_path text,

  monthly_rent numeric(12,2) not null default 0,
  additional_costs numeric(12,2) not null default 0,
  security_deposit numeric(12,2) not null default 0,
  lease_start_date date,
  lease_end_date date,
  office_notes text,

  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists contract_intakes_tenant_idx on public.contract_intakes(tenant_id);
create index if not exists contract_intakes_building_idx on public.contract_intakes(building_id);
create index if not exists contract_intakes_unit_idx on public.contract_intakes(unit_id);
create index if not exists contract_intakes_status_idx on public.contract_intakes(status);

create or replace function public.set_contract_intake_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists contract_intakes_updated_at on public.contract_intakes;
create trigger contract_intakes_updated_at
before update on public.contract_intakes
for each row execute function public.set_contract_intake_updated_at();

alter table public.contract_intakes enable row level security;

drop policy if exists "contract intakes authenticated select" on public.contract_intakes;
drop policy if exists "contract intakes authenticated insert" on public.contract_intakes;
drop policy if exists "contract intakes authenticated update" on public.contract_intakes;
drop policy if exists "contract intakes authenticated delete" on public.contract_intakes;

create policy "contract intakes authenticated select" on public.contract_intakes for select to authenticated using (true);
create policy "contract intakes authenticated insert" on public.contract_intakes for insert to authenticated with check (true);
create policy "contract intakes authenticated update" on public.contract_intakes for update to authenticated using (true) with check (true);
create policy "contract intakes authenticated delete" on public.contract_intakes for delete to authenticated using (true);

grant select,insert,update,delete on public.contract_intakes to authenticated;
grant usage,select on sequence public.contract_intakes_id_seq to authenticated;

-- Public tenant form: token-scoped read. It intentionally does NOT expose office-only fields.
create or replace function public.get_contract_intake_public(p_token text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare r public.contract_intakes;
begin
  begin
    select * into r from public.contract_intakes where public_token = p_token::uuid;
  exception when invalid_text_representation then
    return null;
  end;
  if r.id is null then return null; end if;
  return jsonb_build_object(
    'id',r.id,'status',r.status,
    'tenant_first_name',r.tenant_first_name,'tenant_last_name',r.tenant_last_name,
    'tenant_date_of_birth',r.tenant_date_of_birth,'tenant_id_number',r.tenant_id_number,
    'occupant_count',r.occupant_count,'phone',r.phone,'email',r.email,
    'id_front_path',r.id_front_path,'id_back_path',r.id_back_path,
    'has_additional_tenant',r.has_additional_tenant,
    'additional_tenant_first_name',r.additional_tenant_first_name,
    'additional_tenant_last_name',r.additional_tenant_last_name,
    'additional_tenant_date_of_birth',r.additional_tenant_date_of_birth,
    'additional_tenant_id_number',r.additional_tenant_id_number,
    'additional_id_front_path',r.additional_id_front_path,
    'additional_id_back_path',r.additional_id_back_path
  );
end;
$$;

create or replace function public.save_contract_intake_public(p_token text,p_payload jsonb,p_complete boolean default false)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare r public.contract_intakes;
begin
  begin
    select * into r from public.contract_intakes where public_token = p_token::uuid for update;
  exception when invalid_text_representation then
    raise exception 'Invalid tenant link';
  end;
  if r.id is null then raise exception 'Tenant link not found'; end if;
  if r.status in ('assigned','contract_ready','completed','archived') then raise exception 'This tenant form is already closed'; end if;

  update public.contract_intakes set
    tenant_first_name=nullif(trim(p_payload->>'tenant_first_name'),''),
    tenant_last_name=nullif(trim(p_payload->>'tenant_last_name'),''),
    tenant_date_of_birth=nullif(p_payload->>'tenant_date_of_birth','')::date,
    tenant_id_number=nullif(trim(p_payload->>'tenant_id_number'),''),
    occupant_count=nullif(p_payload->>'occupant_count','')::integer,
    phone=nullif(trim(p_payload->>'phone'),''),
    email=nullif(trim(p_payload->>'email'),''),
    id_front_path=nullif(p_payload->>'id_front_path',''),
    id_back_path=nullif(p_payload->>'id_back_path',''),
    has_additional_tenant=coalesce((p_payload->>'has_additional_tenant')::boolean,false),
    additional_tenant_first_name=nullif(trim(p_payload->>'additional_tenant_first_name'),''),
    additional_tenant_last_name=nullif(trim(p_payload->>'additional_tenant_last_name'),''),
    additional_tenant_date_of_birth=nullif(p_payload->>'additional_tenant_date_of_birth','')::date,
    additional_tenant_id_number=nullif(trim(p_payload->>'additional_tenant_id_number'),''),
    additional_id_front_path=nullif(p_payload->>'additional_id_front_path',''),
    additional_id_back_path=nullif(p_payload->>'additional_id_back_path',''),
    status=case when p_complete then 'submitted' else 'draft' end,
    submitted_at=case when p_complete then coalesce(submitted_at,now()) else submitted_at end
  where id=r.id
  returning * into r;

  return public.get_contract_intake_public(p_token);
end;
$$;

revoke all on function public.get_contract_intake_public(text) from public;
revoke all on function public.save_contract_intake_public(text,jsonb,boolean) from public;
grant execute on function public.get_contract_intake_public(text) to anon,authenticated;
grant execute on function public.save_contract_intake_public(text,jsonb,boolean) to anon,authenticated;

-- Helper used only by the Storage policy so an anonymous upload is allowed only
-- inside a folder named with a real invitation token.
create or replace function public.contract_intake_token_exists(p_token text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(select 1 from public.contract_intakes where public_token::text=p_token and status in ('invited','draft'));
$$;
revoke all on function public.contract_intake_token_exists(text) from public;
grant execute on function public.contract_intake_token_exists(text) to anon,authenticated;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values ('contract-intake-private','contract-intake-private',false,10485760,array['image/jpeg','image/png','image/webp','application/pdf'])
on conflict (id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists "contract intake public upload" on storage.objects;
drop policy if exists "contract intake authenticated read" on storage.objects;
drop policy if exists "contract intake authenticated delete" on storage.objects;

create policy "contract intake public upload" on storage.objects
for insert to anon,authenticated
with check (
  bucket_id='contract-intake-private'
  and public.contract_intake_token_exists((storage.foldername(name))[1])
);

create policy "contract intake authenticated read" on storage.objects
for select to authenticated
using (bucket_id='contract-intake-private');

create policy "contract intake authenticated delete" on storage.objects
for delete to authenticated
using (bucket_id='contract-intake-private');
-- Property Manager Pro - Contract intake update
-- Adds reusable additional-cost descriptions. Does not delete or replace tenant data.

alter table public.contract_intakes
  add column if not exists has_additional_costs boolean not null default false,
  add column if not exists additional_cost_description text;

update public.contract_intakes
set has_additional_costs = true
where coalesce(additional_costs,0) <> 0
  and has_additional_costs = false;

create table if not exists public.contract_cost_options (
  id bigint generated by default as identity primary key,
  description text not null unique,
  created_at timestamptz not null default now()
);

alter table public.contract_cost_options enable row level security;

drop policy if exists "contract cost options authenticated select" on public.contract_cost_options;
drop policy if exists "contract cost options authenticated insert" on public.contract_cost_options;
drop policy if exists "contract cost options authenticated update" on public.contract_cost_options;
drop policy if exists "contract cost options authenticated delete" on public.contract_cost_options;

create policy "contract cost options authenticated select"
on public.contract_cost_options for select to authenticated using (true);

create policy "contract cost options authenticated insert"
on public.contract_cost_options for insert to authenticated with check (true);

create policy "contract cost options authenticated update"
on public.contract_cost_options for update to authenticated using (true) with check (true);

create policy "contract cost options authenticated delete"
on public.contract_cost_options for delete to authenticated using (true);

grant select,insert,update,delete on public.contract_cost_options to authenticated;
grant usage,select on sequence public.contract_cost_options_id_seq to authenticated;


-- Reliable contract assignment + generated-contract metadata
alter table public.contract_intakes
  add column if not exists contract_generated_at timestamptz,
  add column if not exists contract_file_name text;

create or replace function public.assign_contract_intake(
  p_intake_id bigint,
  p_building_id bigint,
  p_unit_id bigint,
  p_monthly_rent numeric default 0,
  p_additional_costs numeric default 0
) returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  r public.contract_intakes;
  v_tenant_id bigint;
begin
  select * into r from public.contract_intakes where id=p_intake_id for update;
  if r.id is null then raise exception 'Contract intake not found'; end if;
  if r.submitted_at is null and r.status not in ('submitted','assigned','contract_ready','completed') then
    raise exception 'Tenant must submit the form before assignment';
  end if;
  if not exists(select 1 from public.buildings where id=p_building_id) then raise exception 'Building not found'; end if;
  if not exists(select 1 from public.units where id=p_unit_id and building_id=p_building_id) then raise exception 'Selected unit does not belong to the selected building'; end if;

  v_tenant_id:=r.tenant_id;
  if v_tenant_id is null then
    insert into public.tenants(name,phone,email,base_rent,additional_costs,rent,active)
    values(trim(concat_ws(' ',r.tenant_first_name,r.tenant_last_name)),coalesce(r.phone,''),coalesce(r.email,''),coalesce(p_monthly_rent,0),coalesce(p_additional_costs,0),coalesce(p_monthly_rent,0)+coalesce(p_additional_costs,0),true)
    returning id into v_tenant_id;
  else
    update public.tenants set
      name=trim(concat_ws(' ',r.tenant_first_name,r.tenant_last_name)),phone=coalesce(r.phone,''),email=coalesce(r.email,''),
      base_rent=coalesce(p_monthly_rent,0),additional_costs=coalesce(p_additional_costs,0),rent=coalesce(p_monthly_rent,0)+coalesce(p_additional_costs,0),active=true
    where id=v_tenant_id;
  end if;

  delete from public.tenant_units where tenant_id=v_tenant_id;
  insert into public.tenant_units(tenant_id,unit_id) values(v_tenant_id,p_unit_id);

  update public.contract_intakes set tenant_id=v_tenant_id,building_id=p_building_id,unit_id=p_unit_id,
    monthly_rent=coalesce(p_monthly_rent,0),additional_costs=coalesce(p_additional_costs,0),
    status=case when status='contract_ready' then 'contract_ready' else 'assigned' end
  where id=p_intake_id;
  return v_tenant_id;
end;
$$;
revoke all on function public.assign_contract_intake(bigint,bigint,bigint,numeric,numeric) from public;
grant execute on function public.assign_contract_intake(bigint,bigint,bigint,numeric,numeric) to authenticated;

-- Owner contract details + multiple named bank accounts
alter table public.owners
  add column if not exists address text,
  add column if not exists postal_code text,
  add column if not exists city text,
  add column if not exists country text default 'België';

create table if not exists public.owner_bank_accounts (
  id bigint generated by default as identity primary key,
  owner_id bigint not null,
  label text not null,
  iban text not null,
  is_default boolean not null default false,
  created_at timestamptz not null default now()
);

-- Add the owner FK only when it is not present already.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname='owner_bank_accounts_owner_id_fkey'
      and conrelid='public.owner_bank_accounts'::regclass
  ) then
    alter table public.owner_bank_accounts
      add constraint owner_bank_accounts_owner_id_fkey
      foreign key (owner_id) references public.owners(id) on delete cascade;
  end if;
end $$;

create unique index if not exists owner_bank_accounts_one_default_per_owner
  on public.owner_bank_accounts(owner_id)
  where is_default;

create unique index if not exists owner_bank_accounts_owner_label_unique
  on public.owner_bank_accounts(owner_id, lower(label));

alter table public.owner_bank_accounts enable row level security;
drop policy if exists "owner bank accounts authenticated select" on public.owner_bank_accounts;
drop policy if exists "owner bank accounts authenticated insert" on public.owner_bank_accounts;
drop policy if exists "owner bank accounts authenticated update" on public.owner_bank_accounts;
drop policy if exists "owner bank accounts authenticated delete" on public.owner_bank_accounts;
create policy "owner bank accounts authenticated select" on public.owner_bank_accounts for select to authenticated using (true);
create policy "owner bank accounts authenticated insert" on public.owner_bank_accounts for insert to authenticated with check (true);
create policy "owner bank accounts authenticated update" on public.owner_bank_accounts for update to authenticated using (true) with check (true);
create policy "owner bank accounts authenticated delete" on public.owner_bank_accounts for delete to authenticated using (true);
grant select,insert,update,delete on public.owner_bank_accounts to authenticated;
grant usage,select on sequence public.owner_bank_accounts_id_seq to authenticated;

-- Preserve any existing single owner IBAN by making it a named default account.
insert into public.owner_bank_accounts(owner_id,label,iban,is_default)
select o.id,'Main account',o.iban,true
from public.owners o
where nullif(trim(coalesce(o.iban,'')),'') is not null
  and not exists(select 1 from public.owner_bank_accounts a where a.owner_id=o.id)
on conflict do nothing;

alter table public.contract_intakes
  add column if not exists owner_bank_account_id bigint;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname='contract_intakes_owner_bank_account_id_fkey'
      and conrelid='public.contract_intakes'::regclass
  ) then
    alter table public.contract_intakes
      add constraint contract_intakes_owner_bank_account_id_fkey
      foreign key (owner_bank_account_id) references public.owner_bank_accounts(id) on delete set null;
  end if;
end $$;


-- Read-only Bank Automation
create table if not exists public.bank_connections (
 id bigint generated by default as identity primary key,
 owner_id bigint references public.owners(id) on delete cascade,
 provider text not null check (provider in ('crelan','ing','enable_banking')),
 display_name text,
 status text not null default 'pending' check (status in ('pending','setup_required','connected','expired','disconnected','error')),
 read_only boolean not null default true check (read_only = true),
 external_session_id text,
 consent_expires_at timestamptz,
 last_sync_at timestamptz,
 error_message text,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);

-- Owner-scoped bank feeds (safe upgrade for existing installations)
alter table public.bank_connections add column if not exists owner_id bigint;
do $$ begin
  if not exists (select 1 from pg_constraint where conname='bank_connections_owner_id_fkey') then
    alter table public.bank_connections add constraint bank_connections_owner_id_fkey foreign key (owner_id) references public.owners(id) on delete cascade;
  end if;
end $$;
-- If this portfolio currently has exactly one owner, attach existing bank connections to that owner.
do $$
declare v_owner bigint; v_count integer;
begin
  select count(*), min(id) into v_count, v_owner from public.owners;
  if v_count=1 then update public.bank_connections set owner_id=v_owner where owner_id is null; end if;
end $$;
create index if not exists bank_connections_owner_idx on public.bank_connections(owner_id);
create table if not exists public.bank_accounts (
 id bigint generated by default as identity primary key,
 connection_id bigint references public.bank_connections(id) on delete cascade,
 external_account_id text,
 identification_hash text,
 bank_name text,
 account_name text,
 iban text,
 currency text default 'EUR',
 balance numeric(16,2),
 balance_updated_at timestamptz,
 active boolean not null default true,
 created_at timestamptz not null default now()
);
create unique index if not exists bank_accounts_connection_external_uidx on public.bank_accounts(connection_id,external_account_id);
create table if not exists public.bank_transactions (
 id bigint generated by default as identity primary key,
 bank_account_id bigint references public.bank_accounts(id) on delete set null,
 external_transaction_id text unique,
 bank_name text,
 booking_date date,
 value_date date,
 amount numeric(16,2) not null default 0,
 currency text not null default 'EUR',
 counterparty_name text,
 counterparty_iban text,
 remittance_information text,
 direction text generated always as (case when amount >= 0 then 'incoming' else 'outgoing' end) stored,
 match_status text not null default 'unmatched' check (match_status in ('unmatched','matched','ignored')),
 matched_tenant_id bigint references public.tenants(id) on delete set null,
 matched_payment_id bigint references public.payments(id) on delete set null,
 matched_at timestamptz,
 raw jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now()
);
create index if not exists bank_transactions_booking_idx on public.bank_transactions(booking_date desc);
create index if not exists bank_transactions_match_idx on public.bank_transactions(match_status);

alter table public.bank_connections enable row level security;
alter table public.bank_accounts enable row level security;
alter table public.bank_transactions enable row level security;
do $$ begin
 create policy "bank connections authenticated" on public.bank_connections for all to authenticated using (true) with check (read_only=true);
exception when duplicate_object then null; end $$;
do $$ begin
 create policy "bank accounts authenticated read" on public.bank_accounts for select to authenticated using (true);
exception when duplicate_object then null; end $$;
do $$ begin
 create policy "bank transactions authenticated read" on public.bank_transactions for select to authenticated using (true);
exception when duplicate_object then null; end $$;
do $$ begin
 create policy "bank transactions authenticated manual import" on public.bank_transactions for insert to authenticated with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
 create policy "bank transactions authenticated match" on public.bank_transactions for update to authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;
grant select,insert,update,delete on public.bank_connections to authenticated;
grant select on public.bank_accounts to authenticated;
grant select,insert,update on public.bank_transactions to authenticated;
grant usage,select on sequence public.bank_connections_id_seq, public.bank_accounts_id_seq, public.bank_transactions_id_seq to authenticated;


-- Tenant payment references + owner bank-feed mapping
alter table public.tenants add column if not exists payment_reference text;
alter table public.tenants add column if not exists communication_language text not null default 'en';
update public.tenants set payment_reference = 'PM-' || upper(substr(md5(random()::text || id::text),1,4)) || '-' || lpad((1000 + floor(random()*9000))::int::text,4,'0') where payment_reference is null or btrim(payment_reference)='';
create unique index if not exists tenants_payment_reference_unique on public.tenants(payment_reference) where payment_reference is not null;

alter table public.bank_accounts add column if not exists owner_bank_account_id bigint;
do $$ begin
  if not exists (select 1 from pg_constraint where conname='bank_accounts_owner_bank_account_id_fkey' and conrelid='public.bank_accounts'::regclass) then
    alter table public.bank_accounts add constraint bank_accounts_owner_bank_account_id_fkey foreign key (owner_bank_account_id) references public.owner_bank_accounts(id) on delete set null;
  end if;
end $$;
create index if not exists bank_accounts_owner_bank_account_idx on public.bank_accounts(owner_bank_account_id);

-- Tenant communications, reminders, tracking and rent indexation
create table if not exists public.tenant_messages (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  subject text,
  body text not null,
  delivery_channel text not null default 'email' check (delivery_channel in ('email','sms','whatsapp','manual')),
  reply_mode text not null default 'allow' check (reply_mode in ('allow','no_reply')),
  status text not null default 'draft' check (status in ('draft','queued','scheduled','sent','delivered','replied','failed','cancelled')),
  scheduled_for timestamptz,
  sent_at timestamptz,
  provider_message_id text,
  tracking_token text not null,
  last_reply_text text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists tenant_messages_tracking_token_uidx on public.tenant_messages(tracking_token);
create index if not exists tenant_messages_tenant_idx on public.tenant_messages(tenant_id,created_at desc);
create table if not exists public.tenant_message_events (
  id bigint generated by default as identity primary key,
  message_id bigint not null references public.tenant_messages(id) on delete cascade,
  event_type text not null check (event_type in ('queued','sent','delivered','opened','link_viewed','replied','bounced','failed')),
  provider_event_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists tenant_message_events_message_idx on public.tenant_message_events(message_id,created_at);
create table if not exists public.tenant_reminders (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  title text not null,
  message_body text not null,
  channel text not null default 'email' check (channel in ('email','sms','whatsapp','manual')),
  reply_mode text not null default 'allow' check (reply_mode in ('allow','no_reply')),
  recurrence text not null default 'none' check (recurrence in ('none','daily','weekly','monthly','yearly')),
  next_run_at timestamptz,
  last_run_at timestamptz,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists tenant_reminders_due_idx on public.tenant_reminders(active,next_run_at);
create table if not exists public.tenant_indexations (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  region text not null default 'flanders',
  epc_label text,
  base_rent numeric(12,2) not null,
  contract_signature_date date,
  contract_start_date date,
  initial_index numeric(12,4),
  new_index numeric(12,4),
  calculated_rent numeric(12,2),
  calculation_date date,
  status text not null default 'calculated' check (status in ('calculated','applied','cancelled')),
  source_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists tenant_indexations_tenant_idx on public.tenant_indexations(tenant_id,created_at desc);

alter table public.tenant_messages enable row level security;
alter table public.tenant_message_events enable row level security;
alter table public.tenant_reminders enable row level security;
alter table public.tenant_indexations enable row level security;
do $$ begin create policy "tenant messages authenticated" on public.tenant_messages for all to authenticated using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "tenant message events authenticated" on public.tenant_message_events for select to authenticated using (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "tenant reminders authenticated" on public.tenant_reminders for all to authenticated using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "tenant indexations authenticated" on public.tenant_indexations for all to authenticated using (true) with check (true); exception when duplicate_object then null; end $$;
grant select,insert,update,delete on public.tenant_messages,public.tenant_reminders,public.tenant_indexations to authenticated;
grant select on public.tenant_message_events to authenticated;
grant usage,select on sequence public.tenant_messages_id_seq,public.tenant_message_events_id_seq,public.tenant_reminders_id_seq,public.tenant_indexations_id_seq to authenticated;
