const {eb,supa}=require("./_lib");
const clean=v=>String(v||"").replace(/\s+/g,"").toLowerCase();
const norm=v=>String(v||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]/g,"");
async function autoPost(tx){
 if(Number(tx.amount||0)<=0)return false;
 const tenants=await supa('tenants?active=eq.true&select=id,name,iban,payment_reference');
 const text=norm([tx.counterparty_name,tx.counterparty_iban,tx.remittance_information].join(' ')), iban=clean(tx.counterparty_iban);
 let matches=[];
 for(const t of tenants||[]){let score=0;const reasons=[];const ref=norm(t.payment_reference),ti=clean(t.iban),name=norm(t.name);
  if(ref&&text.includes(ref)){score+=20;reasons.push('reference')}
  if(ti&&iban&&ti===iban){score+=14;reasons.push('iban')}
  if(name&&text.includes(name)){score+=7;reasons.push('name')}
  const ps=await supa(`payments?tenant_id=eq.${t.id}&select=*&order=year.asc,month.asc`);
  for(const p of ps||[]){const es=await supa(`payment_entries?payment_id=eq.${p.id}&select=amount`);const paid=(es||[]).reduce((a,x)=>a+Number(x.amount||0),0);const due=Math.max(0,Number(p.expected_amount||0)-paid);if(due>.005&&Math.abs(Number(tx.amount)-due)<.01){matches.push({t,p,score:score+6,reasons:[...reasons,'amount'],due});break}}
 }
 matches.sort((a,b)=>b.score-a.score);const b=matches[0],second=matches[1];
 // Auto-post only with a unique, high-confidence identity match plus exact expected amount.
 if(!b||!b.reasons.includes('amount')||(!b.reasons.includes('reference')&&!b.reasons.includes('iban'))||b.score<20||(second&&b.score-second.score<5))return false;
 await supa('payment_entries',{method:'POST',body:JSON.stringify({payment_id:b.p.id,amount:Number(tx.amount),payment_date:tx.booking_date||new Date().toISOString().slice(0,10),method:'bank',reference:tx.remittance_information||tx.external_transaction_id||'',notes:`Auto-matched bank payment · ${b.reasons.join(', ')}`})});
 const entries=await supa(`payment_entries?payment_id=eq.${b.p.id}&select=amount`),paid=(entries||[]).reduce((a,x)=>a+Number(x.amount||0),0),due=Number(b.p.expected_amount||0);
 await supa(`payments?id=eq.${b.p.id}`,{method:'PATCH',body:JSON.stringify({paid_amount:paid,status:paid>=due-.005?'paid':paid>0?'partial':'pending'})});
 await supa(`bank_transactions?id=eq.${tx.id}`,{method:'PATCH',body:JSON.stringify({match_status:'matched',matched_tenant_id:b.t.id,matched_payment_id:b.p.id,matched_at:new Date().toISOString()})});return true;
}
module.exports=async(req,res)=>{try{if(req.method!=="POST")return res.status(405).json({error:"POST required"});const id=String(req.query.connection_id||"");if(!/^\d+$/.test(id))return res.status(400).json({error:"Invalid connection"});const conns=await supa(`bank_connections?id=eq.${id}&select=*`),c=conns?.[0];if(!c?.external_session_id)throw new Error("Bank connection is not authorized");const accts=await supa(`bank_accounts?connection_id=eq.${id}&select=*`);let imported=0,autoMatched=0;for(const a of accts||[]){if(a.active===false||!a.external_account_id)continue;try{const b=await eb(`/accounts/${encodeURIComponent(a.external_account_id)}/balances`);const bal=(b.balances||[]).find(x=>["CLBD","CLAV","ITAV"].includes(x.balance_type))||(b.balances||[])[0];if(bal)await supa(`bank_accounts?id=eq.${a.id}`,{method:"PATCH",body:JSON.stringify({balance:Number(bal.balance_amount?.amount||0),currency:bal.balance_amount?.currency||a.currency||"EUR",balance_updated_at:new Date().toISOString()})})}catch(e){console.error("balance",e.message)}let continuation=null,loops=0;do{let path=`/accounts/${encodeURIComponent(a.external_account_id)}/transactions?date_from=${new Date(Date.now()-120*86400000).toISOString().slice(0,10)}`;if(continuation)path+=`&continuation_key=${encodeURIComponent(continuation)}`;const d=await eb(path);for(const t of d.transactions||[]){const amount=Number(t.transaction_amount?.amount||0)*(String(t.credit_debit_indicator||"").toUpperCase()==="DBIT"?-1:1);const cp=t.debtor?.name||t.creditor?.name||t.debtor_name||t.creditor_name||"",iban=t.debtor_account?.iban||t.creditor_account?.iban||"",remit=Array.isArray(t.remittance_information)?t.remittance_information.join(" · "):t.remittance_information_unstructured||t.remittance_information||"",ext=t.entry_reference||t.transaction_id||`${a.external_account_id}-${t.booking_date||t.booking_date_time}-${amount}-${remit}`;await supa("bank_transactions?on_conflict=external_transaction_id",{method:"POST",prefer:"resolution=ignore-duplicates,return=minimal",body:JSON.stringify({bank_account_id:a.id,external_transaction_id:String(ext),bank_name:a.bank_name,booking_date:String(t.booking_date||t.booking_date_time||new Date().toISOString()).slice(0,10),value_date:String(t.value_date||t.value_date_time||"").slice(0,10)||null,amount,currency:t.transaction_amount?.currency||a.currency||"EUR",counterparty_name:cp,counterparty_iban:iban,remittance_information:remit,raw:t})});imported++}continuation=d.continuation_key||null;loops++}while(continuation&&loops<10)}
 const fresh=await supa(`bank_transactions?bank_account_id=in.(${(accts||[]).map(x=>x.id).join(',')||0})&match_status=eq.unmatched&amount=gt.0&select=*`);for(const tx of fresh||[])try{if(await autoPost(tx))autoMatched++}catch(e){console.error('auto-match',tx.id,e.message)}
 await supa(`bank_connections?id=eq.${id}`,{method:"PATCH",body:JSON.stringify({last_sync_at:new Date().toISOString(),status:"connected",error_message:null})});res.status(200).json({ok:true,imported,autoMatched})}catch(e){res.status(500).json({error:e.message})}};
