'use strict';
const {supa,event,workspaceReplyTo}=require('./core');
function inboundConfigured(){return Boolean(process.env.REMINDER_REPLY_DOMAIN&&process.env.RESEND_API_KEY&&process.env.RESEND_WEBHOOK_SECRET)}
function emailAddress(value){const m=String(value||'').match(/<([^<>]+)>/);const e=String(m?m[1]:value||'').trim().toLowerCase();return /^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(e)?e:''}
function routingMarkers(body){return (String(body||'').match(/\n?__MR4U_(?:THREAD|PARENT):[0-9]+__/g)||[]).join('')}
function cleanRouting(body){return String(body||'').replace(/\n?__MR4U_(?:THREAD|PARENT):[0-9]+__/g,'').trim()}
function threadId(m){return (String(m?.body||'').match(/__MR4U_THREAD:([0-9]+)__/)||[])[1]||String(m?.id||'')}
function htmlText(html){let s=String(html||'');if(/^data:text\/html[^,]*,/i.test(s)){const [head,...tail]=s.split(',');s=/;base64/i.test(head)?Buffer.from(tail.join(','),'base64').toString('utf8'):decodeURIComponent(tail.join(','))}return s.replace(/<(script|style)\b[^>]*>[\s\S]*?<\/\1>/gi,'').replace(/<br\s*\/?\s*>|<\/(?:p|div|li|tr|h[1-6])>/gi,'\n').replace(/<[^>]+>/g,'').replace(/&nbsp;/gi,' ').replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&amp;/gi,'&').replace(/\n{3,}/g,'\n\n').trim()}
function replyText(text){const lines=String(text||'').replace(/\r\n/g,'\n').split('\n');let cut=lines.length;for(let i=0;i<lines.length;i++){if(/^\s*(?:On .+wrote:|Op .+schreef.*:|Le .+écrit\s*:|Am .+schrieb.*:|[-_]{3,}\s*(?:Original Message|Forwarded message)|>)/i.test(lines[i])){cut=i;break}if(/^\s*On\s/i.test(lines[i])&&lines.slice(i,i+4).join(' ').match(/wrote:\s*$/i)){cut=i;break}}return lines.slice(0,cut).join('\n').trim()||String(text||'').trim()}
async function resend(path,options={}){if(!process.env.RESEND_API_KEY)throw Error('Missing RESEND_API_KEY');const r=await fetch('https://api.resend.com'+path,{...options,headers:{Authorization:'Bearer '+process.env.RESEND_API_KEY,'Content-Type':'application/json',...(options.headers||{})}});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.message||'Email provider returned '+r.status);return j}
async function replyHeaders(m){const parent=(String(m.body||'').match(/__MR4U_PARENT:([0-9]+)__/)||[])[1];if(!parent)return{};const rows=await supa(`tenant_messages?id=eq.${parent}&tenant_id=eq.${m.tenant_id}&workspace_id=eq.${m.workspace_id}&select=*`);const original=rows?.[0];if(!original)return{};const es=await supa(`tenant_message_events?message_id=eq.${parent}&workspace_id=eq.${m.workspace_id}&event_type=eq.replied&order=created_at.desc`);let reference=(es||[]).map(e=>e.metadata?.rfc_message_id).find(Boolean);if(!reference&&original.provider_message_id){try{reference=(await resend('/emails/'+encodeURIComponent(original.provider_message_id))).message_id}catch{}}if(!reference||/[\r\n]/.test(reference))return{};return {'In-Reply-To':reference,References:reference}}
async function ingestReply(payload){
 if(!inboundConfigured())throw Error('Incoming replies require REMINDER_REPLY_DOMAIN, RESEND_API_KEY and RESEND_WEBHOOK_SECRET.');
 const data=payload.data||{},domain=String(process.env.REMINDER_REPLY_DOMAIN).trim().toLowerCase(),recipients=(Array.isArray(data.to)?data.to:[data.to]).filter(Boolean).map(emailAddress);
 const address=recipients.find(e=>e.endsWith('@'+domain)&&/^reply\+[a-z0-9-]+@/i.test(e));if(!address)return {ignored:true};
 const token=address.slice(6,address.lastIndexOf('@'));const messages=await supa(`tenant_messages?tracking_token=eq.${encodeURIComponent(token)}&select=*`),m=messages?.[0];if(!m)return {ignored:true};
 const emailId=String(data.email_id||'');if(!/^[a-z0-9-]+$/i.test(emailId))throw Error('Received email id is missing or invalid.');
 const previous=await supa(`tenant_message_events?message_id=eq.${m.id}&workspace_id=eq.${m.workspace_id}&event_type=eq.replied&metadata->>received_email_id=eq.${encodeURIComponent(emailId)}&select=*`);let record=previous?.[0];
 let received=null;if(!record){received=await resend('/emails/receiving/'+encodeURIComponent(emailId));const full=String(received.text||htmlText(received.html)||'').slice(0,100000),text=replyText(full),forwardTo=await workspaceReplyTo(m.workspace_id);
 const metadata={received_email_id:emailId,provider_event_id:payload.id||null,from:String(received.from||data.from||''),to:received.to||data.to||[],cc:received.cc||[],subject:String(received.subject||data.subject||m.subject||'Reply'),text,full_text:full,received_at:received.created_at||payload.created_at||new Date().toISOString(),rfc_message_id:received.message_id||'',thread_id:threadId(m),forward_to:forwardTo,attachments:(received.attachments||[]).map(a=>({id:a.id,name:a.filename||'Attachment',type:a.content_type||'',size:a.size||0})),forwarded:false};
 const saved=await event(m.id,'replied',metadata);record=Array.isArray(saved)?saved[0]:saved;if(!record?.id)throw Error('Incoming reply could not be saved.');
 }
 const meta=record.metadata||{};await supa(`tenant_messages?id=eq.${m.id}&workspace_id=eq.${m.workspace_id}`,{method:'PATCH',body:JSON.stringify({status:'replied',last_reply_text:meta.text||'',updated_at:new Date().toISOString()})});
 if(!meta.forwarded){const to=emailAddress(meta.forward_to||await workspaceReplyTo(m.workspace_id));if(to&&to!==address){const from=process.env.RESEND_FROM_EMAIL||process.env.REMINDER_FROM_EMAIL;if(!from)throw Error('Email sender is not configured.');const sender=emailAddress(meta.from);const attachmentNote=(meta.attachments||[]).length?'\n\nAttachments: '+meta.attachments.map(a=>a.name).join(', '):'';
 const forwardedAttachments=[];let attachmentBytes=0;for(const a of meta.attachments||[]){if(!a.id)continue;const details=await resend('/emails/receiving/'+encodeURIComponent(emailId)+'/attachments/'+encodeURIComponent(a.id));if(!details.download_url)throw Error('Incoming attachment download is unavailable.');const download=await fetch(details.download_url);if(!download.ok)throw Error('Incoming attachment could not be downloaded.');const bytes=Buffer.from(await download.arrayBuffer());attachmentBytes+=bytes.length;if(attachmentBytes>40*1024*1024)throw Error('Incoming attachments exceed the forwarding limit.');forwardedAttachments.push({filename:a.name,content:bytes.toString('base64')});}
 const forwarded=await resend('/emails',{method:'POST',headers:{'Idempotency-Key':'mr4u-incoming-'+emailId},body:JSON.stringify({from,to:[to],subject:meta.subject||'Tenant reply',text:`From: ${meta.from}\nTo: ${to}\nReceived: ${meta.received_at}\n\n${meta.full_text||meta.text||'(No text content)'}${attachmentNote}\n\nThis reply is also saved in the ManageRent4U conversation.`,...(forwardedAttachments.length?{attachments:forwardedAttachments}:{}),...(sender?{reply_to:sender}:{})})});
 const next={...meta,forwarded:true,forwarded_to:to,forwarded_email_id:forwarded.id};await supa(`tenant_message_events?id=eq.${record.id}&workspace_id=eq.${m.workspace_id}`,{method:'PATCH',body:JSON.stringify({metadata:next})});
 }}return {ok:true,stored:true,message_id:m.id};
}
module.exports={inboundConfigured,emailAddress,routingMarkers,cleanRouting,threadId,replyHeaders,ingestReply,replyText,htmlText};
