const crypto=require('crypto');
function base(){let u=String(process.env.SUPABASE_URL||'').trim().replace(/\/+$/,'').replace(/\/rest\/v1$/i,'');if(!u)throw new Error('Missing SUPABASE_URL');return u}
function key(){const k=String(process.env.SUPABASE_SERVICE_ROLE_KEY||'').trim();if(!k)throw new Error('Missing SUPABASE_SERVICE_ROLE_KEY');return k}
async function supa(path,options={}){const k=key(),clean=String(path||'').replace(/^\/+/, '').replace(/^rest\/v1\//i,'');const headers={apikey:k,'Content-Type':'application/json',Prefer:options.prefer||'return=representation',...(options.headers||{})};if(!k.startsWith('sb_secret_'))headers.Authorization=`Bearer ${k}`;const r=await fetch(`${base()}/rest/v1/${clean}`,{...options,headers});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{data={message:text}}if(!r.ok)throw new Error(data?.message||data?.details||`Supabase ${r.status}`);return data}
async function requireUser(req){const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!token)throw new Error('Not signed in');const k=key();const r=await fetch(`${base()}/auth/v1/user`,{headers:{apikey:k,Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error('Invalid session');return r.json()}
function appUrl(){return String(process.env.BANK_APP_URL||process.env.APP_BASE_URL||'').replace(/\/+$/,'')}
function trackingUrl(type,token){return `${appUrl()}/api/messages/${type}?token=${encodeURIComponent(token)}`}
function replyAddress(token){const domain=String(process.env.REMINDER_REPLY_DOMAIN||'').trim();return domain?`reply+${token}@${domain}`:(process.env.REMINDER_REPLY_TO||'')}
async function event(message_id,event_type,metadata={}){const m=(await supa(`tenant_messages?id=eq.${message_id}&select=workspace_id`))?.[0];return supa('tenant_message_events',{method:'POST',body:JSON.stringify({workspace_id:m?.workspace_id||null,message_id,event_type,metadata})})}
function verifySvix(raw,headers){const secret=String(process.env.RESEND_WEBHOOK_SECRET||'');if(!secret)return true;const id=headers['svix-id'],ts=headers['svix-timestamp'],sig=headers['svix-signature'];if(!id||!ts||!sig)return false;const b64=secret.startsWith('whsec_')?secret.slice(6):secret;const key=Buffer.from(b64,'base64');const expected=crypto.createHmac('sha256',key).update(`${id}.${ts}.${raw}`).digest('base64');return String(sig).split(' ').some(part=>{const v=part.split(',')[1];if(!v)return false;try{return crypto.timingSafeEqual(Buffer.from(v),Buffer.from(expected))}catch{return false}})}
module.exports={supa,requireUser,appUrl,trackingUrl,replyAddress,event,verifySvix};
