import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import{createClient}from'@supabase/supabase-js';
import'./style.css';
const supabase=createClient('https://yiileradnxvlvkikyuwi.supabase.co','sb_publishable_bCyn05Ht69i9AmFvQhf2IQ_s_MnTsuD');
function App(){const[session,setSession]=useState(null),[db,setDb]=useState({owners:[],buildings:[],units:[]}),[page,setPage]=useState('dashboard'),[modal,setModal]=useState(null),[q,setQ]=useState('');
useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);if(data.session)load()});const{data}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);if(s)load()});return()=>data.subscription.unsubscribe()},[]);
async function load(){const[o,b,u]=await Promise.all([supabase.from('owners').select('*').order('id'),supabase.from('buildings').select('*').order('id'),supabase.from('units').select('*').order('id')]);setDb({owners:o.data||[],buildings:b.data||[],units:u.data||[]})}
if(!session)return <Login/>;
return <div className="app"><aside><div className="brand"><div className="logo">🏠</div><div><h2>Property Manager Pro</h2><small>{session.user.email}</small></div></div><input className="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search..."/><button onClick={()=>setPage('dashboard')}>🏠 Dashboard</button><button onClick={()=>setPage('owners')}>👤 Owners</button><button onClick={()=>setPage('buildings')}>🏢 Buildings</button><button onClick={()=>setPage('units')}>🚪 Units</button><button onClick={()=>supabase.auth.signOut()}>Logout</button><h4>Portfolio</h4><Portfolio db={db} q={q} setModal={setModal}/></aside><main><header><div><h1>{pageTitle(page)}</h1><small>React Sprint 1</small></div><div className="actions"><button className="primary" onClick={()=>setModal({type:'owner'})}>+ Owner</button><button onClick={()=>setModal({type:'building'})}>+ Building</button><button onClick={()=>setModal({type:'unit'})}>+ Unit</button></div></header><section className="content">{page==='dashboard'&&<Dashboard db={db} setModal={setModal}/>} {page==='owners'&&<Owners db={db} setModal={setModal}/>} {page==='buildings'&&<Buildings db={db} setModal={setModal}/>} {page==='units'&&<Units db={db} setModal={setModal}/>}</section></main>{modal&&<EditModal modal={modal} setModal={setModal} db={db} reload={load}/>}</div>}
function pageTitle(p){return{dashboard:'Dashboard',owners:'Owners',buildings:'Buildings',units:'Units'}[p]||'Dashboard'}
function Login(){const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[err,setErr]=useState('');async function login(){setErr('');const{error}=await supabase.auth.signInWithPassword({email,password});if(error)setErr(error.message)}return <div className="login"><div className="login-card"><h1>🏠 Property Manager Pro</h1><p>React clean rebuild</p><label>Email<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary full" onClick={login}>Login</button>{err&&<div className="error">{err}</div>}</div></div>}
function Dashboard({db,setModal}){return <><div className="grid"><Card l="Owners" v={db.owners.length}/><Card l="Buildings" v={db.buildings.length}/><Card l="Units" v={db.units.length}/><Card l="Sprint" v="1"/></div><Panel title="Quick Actions"><div className="tiles"><div className="tile" onClick={()=>setModal({type:'owner'})}><b>+ Owner</b><br/>Add owner</div><div className="tile" onClick={()=>setModal({type:'building'})}><b>+ Building</b><br/>Add building</div><div className="tile" onClick={()=>setModal({type:'unit'})}><b>+ Unit</b><br/>Add unit</div></div></Panel><Panel title="Scope">Sprint 1 is only Owners, Buildings, Units. Tenants and payments come after this saves correctly.</Panel></>}
function Owners({db,setModal}){return <List title="Owners" add={()=>setModal({type:'owner'})}>{db.owners.map(o=><Row key={o.id} t={o.name||'Owner'} s={`${o.email||''} ${o.phone||''}`} onClick={()=>setModal({type:'owner',item:o})}/>)}</List>}
function Buildings({db,setModal}){return <List title="Buildings" add={()=>setModal({type:'building'})}>{db.buildings.map(b=>{const o=db.owners.find(x=>x.id===b.owner_id),c=db.units.filter(u=>u.building_id===b.id).length;return <Row key={b.id} t={b.name||'Building'} s={`${o?.name||'No owner'} · ${c} units · ${b.address||''}`} onClick={()=>setModal({type:'building',item:b})}/>})}</List>}
function Units({db,setModal}){return <List title="Units" add={()=>setModal({type:'unit'})}>{db.units.map(u=>{const b=db.buildings.find(x=>x.id===u.building_id);return <Row key={u.id} t={`${b?.name||'Building'} · Unit ${u.unit_number||''}`} s={u.floor||''} onClick={()=>setModal({type:'unit',item:u})}/>})}</List>}
function Portfolio({db,q,setModal}){const s=q.toLowerCase();return <div>{db.owners.filter(o=>!s||String(o.name||'').toLowerCase().includes(s)).map(o=><div key={o.id}><div className="tree" onClick={()=>setModal({type:'owner',item:o})}>👤 {o.name||'Owner'}</div><div className="child">{db.buildings.filter(b=>b.owner_id===o.id).map(b=><div key={b.id}><div className="tree" onClick={()=>setModal({type:'building',item:b})}>🏢 {b.name||'Building'}</div><div className="child">{db.units.filter(u=>u.building_id===b.id).map(u=><div key={u.id} className="tree" onClick={()=>setModal({type:'unit',item:u})}>🚪 {u.unit_number||'Unit'}</div>)}</div></div>)}</div></div>)}</div>}
function EditModal({modal,setModal,db,reload}){const[item,setItem]=useState(modal.item||{});function set(k,v){setItem(x=>({...x,[k]:v}))}async function save(){const table=modal.type+'s',payload=payloadFor(modal.type,item);let res=modal.item?.id?await supabase.from(table).update(payload).eq('id',modal.item.id):await supabase.from(table).insert(payload);if(res.error)return alert(res.error.message);await reload();setModal(null)}async function del(){if(!confirm('Delete?'))return;const res=await supabase.from(modal.type+'s').delete().eq('id',modal.item.id);if(res.error)return alert(res.error.message);await reload();setModal(null)}return <div className="modal-bg"><div className="modal"><div className="modal-head"><h3>{modal.item?'Edit':'Add'} {modal.type}</h3><button onClick={()=>setModal(null)}>×</button></div><div className="modal-body">{modal.type==='owner'&&<><label>Name<input value={item.name||''} onChange={e=>set('name',e.target.value)}/></label><label>Email<input value={item.email||''} onChange={e=>set('email',e.target.value)}/></label><label>Phone<input value={item.phone||''} onChange={e=>set('phone',e.target.value)}/></label><label>IBAN<input value={item.iban||''} onChange={e=>set('iban',e.target.value)}/></label><label className="wide">Notes<textarea value={item.notes||''} onChange={e=>set('notes',e.target.value)}/></label></>}{modal.type==='building'&&<><label>Owner<select value={item.owner_id||''} onChange={e=>set('owner_id',e.target.value?Number(e.target.value):null)}><option value="">No owner</option>{db.owners.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>Name<input value={item.name||''} onChange={e=>set('name',e.target.value)}/></label><label className="wide">Address<input value={item.address||''} onChange={e=>set('address',e.target.value)}/></label></>}{modal.type==='unit'&&<><label>Building<select value={item.building_id||''} onChange={e=>set('building_id',e.target.value?Number(e.target.value):null)}><option value="">Choose building</option>{db.buildings.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Unit number<input value={item.unit_number||''} onChange={e=>set('unit_number',e.target.value)}/></label><label>Floor<input value={item.floor||''} onChange={e=>set('floor',e.target.value)}/></label></>}</div><div className="modal-foot">{modal.item?.id&&<button className="danger" onClick={del}>Delete</button>}<span/><button onClick={()=>setModal(null)}>Cancel</button><button className="primary" onClick={save}>Save</button></div></div></div>}
function payloadFor(type,f){if(type==='owner')return{name:f.name||'',email:f.email||'',phone:f.phone||'',iban:f.iban||'',notes:f.notes||''};if(type==='building')return{owner_id:f.owner_id||null,name:f.name||'',address:f.address||''};if(type==='unit')return{building_id:f.building_id||null,unit_number:f.unit_number||'',floor:f.floor||''};return f}
function Card({l,v}){return <div className="card"><small>{l}</small><b>{v}</b></div>}function Panel({title,children}){return <div className="panel"><div className="panel-head"><h3>{title}</h3></div><div className="panel-body">{children}</div></div>}function List({title,add,children}){return <div className="panel"><div className="panel-head"><h3>{title}</h3><button className="primary" onClick={add}>+ Add</button></div>{React.Children.count(children)?children:<div className="empty">Nothing yet.</div>}</div>}function Row({t,s,onClick}){return <div className="row" onClick={onClick}><b>{t}</b><span>{s}</span></div>}
createRoot(document.getElementById('root')).render(<App/>);
