'use strict';
const handlers = {};

handlers["send"] = (() => { const module = {exports:{}}; const exports = module.exports;
const {supa,requireUser,trackingUrl,replyAddress,event}=require('../lib/core');
const {PDFDocument,StandardFonts,rgb}=require('pdf-lib');
const esc=s=>String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const eur=n=>new Intl.NumberFormat('nl-BE',{style:'currency',currency:'EUR'}).format(Number(n||0));
function fmtDate(v,lang='en'){if(!v)return '—';try{return new Date(String(v).slice(0,10)+'T12:00:00').toLocaleDateString(lang==='nl'?'nl-BE':lang==='fr'?'fr-BE':'en-GB',{day:'2-digit',month:'long',year:'numeric'})}catch{return String(v)}}
async function ownerForTenant(t){try{let unitId=t?.unit_id||null;if(!unitId){const rel=await supa(`tenant_units?tenant_id=eq.${t.id}&select=unit_id&limit=1`);unitId=rel?.[0]?.unit_id}if(!unitId)return null;const units=await supa(`units?id=eq.${unitId}&select=building_id&limit=1`),buildingId=units?.[0]?.building_id;if(!buildingId)return null;const buildings=await supa(`buildings?id=eq.${buildingId}&select=owner_id&limit=1`),ownerId=buildings?.[0]?.owner_id;if(!ownerId)return null;return (await supa(`owners?id=eq.${ownerId}&select=name,email,phone,address,postal_code,city,country&limit=1`))?.[0]||null}catch{return null}}
function wrap(text,max=82){const words=String(text||'').split(/\s+/),lines=[];let line='';for(const w of words){if(!line){line=w;continue}if((line+' '+w).length>max){lines.push(line);line=w}else line+=' '+w}if(line)lines.push(line);return lines}
async function indexationAttachments(t,owner,idx){if(!idx)return[];const lang=['en','fr','nl'].includes(t.communication_language)?t.communication_language:'en';const base=Number(idx.base_rent||t.base_rent||0),calc=Number(idx.calculated_rent||0),costs=Number(t.additional_costs||0),total=calc+costs,effective=idx.effective_date||idx.contract_start_date||t.tenancy_start_date||'';
 const copy=lang==='nl'?{title:`Jaarlijkse huurindexatie vanaf ${fmtDate(effective,'nl')}`,hello:`Beste ${t.name},`,intro:'Conform de huurovereenkomst informeren wij u over de jaarlijkse aanpassing van de basishuur op basis van de gezondheidsindex.',cur:'Huidige maandelijkse basishuur',next:'Geïndexeerde maandelijkse basishuur',cost:'Bijkomende maandelijkse kosten',tot:'Nieuw maandelijks totaal',source:'Deze aanpassing werd berekend op basis van de officiële gezondheidsindex gepubliceerd door Statbel.',pay:`Gelieve de huur verder te storten met dezelfde gestructureerde mededeling ${t.payment_reference||''}.`,close:'Met vriendelijke groet'}:lang==='fr'?{title:`Indexation annuelle du loyer à partir du ${fmtDate(effective,'fr')}`,hello:`Bonjour ${t.name},`,intro:"Conformément au contrat de location, nous vous informons de l'adaptation annuelle du loyer de base sur la base de l'indice santé.",cur:'Loyer mensuel de base actuel',next:'Loyer mensuel de base indexé',cost:'Charges mensuelles complémentaires',tot:'Nouveau total mensuel',source:"Cette adaptation a été calculée sur la base de l'indice santé officiel publié par Statbel.",pay:`Veuillez continuer à utiliser la communication structurée ${t.payment_reference||''}.`,close:'Bien cordialement'}:{title:`Annual rent indexation from ${fmtDate(effective,'en')}`,hello:`Dear ${t.name},`,intro:'In accordance with the tenancy agreement, we are informing you of the annual adjustment of the basic rent using the health index.',cur:'Current monthly basic rent',next:'Indexed monthly basic rent',cost:'Additional monthly costs',tot:'New monthly total',source:'This adjustment was calculated using the official health index published by Statbel.',pay:`Please continue to use payment reference ${t.payment_reference||''}.`,close:'Kind regards'};
 const pdf=await PDFDocument.create(),font=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold);function page(){return pdf.addPage([595.28,841.89])}function txt(pg,text,x,y,size=11,f=font,color=rgb(.12,.21,.34)){pg.drawText(String(text||''),{x,y,size,font:f,color});return y}function para(pg,text,y,size=11){for(const line of wrap(text,86)){txt(pg,line,56,y,size);y-=17}return y-7}
 let pg=page(),y=790;txt(pg,'MANAGERENT4U',56,y,10,bold,rgb(.08,.37,.82));y-=42;for(const line of wrap(copy.title,46)){txt(pg,line,56,y,20,bold);y-=25}y-=12;y=para(pg,copy.hello,y);y=para(pg,copy.intro,y);const rows=[[copy.cur,eur(base)],[copy.next,eur(calc)]];if(costs)rows.push([copy.cost,eur(costs)],[copy.tot,eur(total)]);rows.push(['Payment reference',t.payment_reference||'—']);for(const [a,b] of rows){txt(pg,a,62,y,10,font,rgb(.35,.43,.53));txt(pg,b,365,y,11,bold);y-=24}y-=10;y=para(pg,copy.source,y);y=para(pg,copy.pay,y);y-=8;txt(pg,copy.close+',',56,y,11);y-=20;txt(pg,owner?.name||'Property Manager',56,y,11,bold);
 pg=page();y=790;txt(pg,'STATBEL CALCULATION SNAPSHOT',56,y,10,bold,rgb(.08,.37,.82));y-=44;txt(pg,'Rent indexation calculation',56,y,21,bold);y-=45;const evidence=[['Basic rent',eur(base)],['Initial health index',String(idx.initial_index||'—')],['New health index',String(idx.new_index||'—')],['Calculated indexed rent',eur(calc)],['Effective date',fmtDate(effective,lang)]];for(const [a,b] of evidence){txt(pg,a,62,y,10,font,rgb(.35,.43,.53));txt(pg,b,330,y,11,bold);y-=28}y-=12;txt(pg,'Formula',62,y,10,bold);y-=22;txt(pg,`${base.toFixed(2)} x ${idx.new_index||'—'} / ${idx.initial_index||'—'} = ${calc.toFixed(2)}`,62,y,13,bold,rgb(.04,.18,.34));y-=44;y=para(pg,'Source: Statbel health-index data / official rent calculator. This snapshot is generated by ManageRent4U from the official index values used in the calculation.',y,9);
 const bytes=await pdf.save();const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="700"><rect width="100%" height="100%" fill="#f4f7fb"/><rect x="70" y="60" width="1060" height="580" rx="28" fill="white" stroke="#dbe5ef"/><text x="110" y="120" font-family="Arial" font-size="22" font-weight="700" fill="#1768df">STATBEL CALCULATION SNAPSHOT</text><text x="110" y="175" font-family="Arial" font-size="34" font-weight="700" fill="#142d4d">Rent indexation calculation</text><text x="110" y="250" font-family="Arial" font-size="22" fill="#53677f">Basic rent</text><text x="890" y="250" text-anchor="end" font-family="Arial" font-size="24" font-weight="700" fill="#142d4d">${esc(eur(base))}</text><text x="110" y="310" font-family="Arial" font-size="22" fill="#53677f">Initial health index</text><text x="890" y="310" text-anchor="end" font-family="Arial" font-size="24" font-weight="700" fill="#142d4d">${esc(idx.initial_index||'—')}</text><text x="110" y="370" font-family="Arial" font-size="22" fill="#53677f">New health index</text><text x="890" y="370" text-anchor="end" font-family="Arial" font-size="24" font-weight="700" fill="#142d4d">${esc(idx.new_index||'—')}</text><rect x="110" y="410" width="850" height="90" rx="16" fill="#0d3155"/><text x="535" y="466" text-anchor="middle" font-family="monospace" font-size="27" font-weight="700" fill="white">${base.toFixed(2)} x ${esc(idx.new_index||'—')} / ${esc(idx.initial_index||'—')} = ${calc.toFixed(2)}</text><text x="110" y="555" font-family="Arial" font-size="22" fill="#53677f">Indexed rent</text><text x="890" y="555" text-anchor="end" font-family="Arial" font-size="25" font-weight="700" fill="#1768df">${esc(eur(calc))}</text><text x="110" y="610" font-family="Arial" font-size="14" fill="#8190a2">Source: official Statbel health-index data used by ManageRent4U.</text></svg>`;
 return[{filename:'rent-indexation-notice.pdf',content:Buffer.from(bytes).toString('base64')},{filename:'statbel-calculation-snapshot.svg',content:Buffer.from(svg).toString('base64')}]
}
module.exports=async(req,res)=>{res.setHeader('Cache-Control','no-store');if(req.method!=='POST')return res.status(405).json({error:'POST required'});try{const user=await requireUser(req);const prof=(await supa(`user_profiles?user_id=eq.${encodeURIComponent(user.id)}&select=active_workspace_id`))?.[0];if(!prof?.active_workspace_id)throw new Error('No active workspace');if(!process.env.RESEND_API_KEY)throw new Error('Email sender is not configured.');const from=process.env.RESEND_FROM_EMAIL||process.env.REMINDER_FROM_EMAIL;if(!from)throw new Error('Email sender is not configured.');const id=Number(req.body?.message_id);const rows=await supa(`tenant_messages?id=eq.${id}&workspace_id=eq.${prof.active_workspace_id}&select=*`),m=rows?.[0];if(!m)throw new Error('Message not found');const tenants=await supa(`tenants?id=eq.${m.tenant_id}&workspace_id=eq.${prof.active_workspace_id}&select=*`),t=tenants?.[0];if(!t?.email)throw new Error('Tenant has no email address');const open=trackingUrl('open',m.tracking_token),owner=await ownerForTenant(t),ownerName=String(owner?.name||'').trim(),rawBody=String(m.body||'').replace(/(Thank you,|Merci,|Dank u,|Kind regards,|Bien cordialement,|Met vriendelijke groeten?,)\s*\nManageRent4U\s*$/i,(x,g)=>`${g}\n${ownerName||'Property Manager'}`),body=esc(rawBody).replace(/\n/g,'<br>'),subject=esc(m.subject||'ManageRent4U message'),reference=String(t.payment_reference||'').trim();
 const html=`<!doctype html><html><body style="margin:0;background:#f3f6fa;font-family:Arial,Helvetica,sans-serif;color:#172b4d"><div style="padding:38px 14px"><div style="max-width:680px;margin:auto;background:#fff;border:1px solid #e1e8f0;border-radius:20px;overflow:hidden;box-shadow:0 16px 44px rgba(15,35,65,.08)"><div style="padding:24px 30px;background:linear-gradient(135deg,#092846,#123e6c);color:#fff"><div style="font-size:11px;letter-spacing:1.7px;font-weight:800;opacity:.78">MANAGERENT4U</div><div style="font-size:25px;line-height:1.25;font-weight:800;margin-top:9px">${subject}</div></div><div style="padding:30px;font-size:15px;line-height:1.72;color:#29435f"><div>${body}</div></div><div style="padding:18px 30px;border-top:1px solid #edf1f5;color:#8a98a8;font-size:11px;background:#fbfcfe">ManageRent4U · Secure property communication</div></div></div><img src="${open}" width="1" height="1" alt="" style="display:none"></body></html>`;
 const payload={from,to:[t.email],subject:m.subject||'ManageRent4U message',html};const reply=replyAddress(m.tracking_token);if(m.reply_mode==='allow'&&reply)payload.reply_to=reply;const context=(String(m.subject||'')+' '+rawBody).toLowerCase();if(/indexation|indexatie|indexation annuelle|huurindexatie/.test(context)){const idx=(await supa(`tenant_indexations?tenant_id=eq.${t.id}&workspace_id=eq.${prof.active_workspace_id}&select=*&order=created_at.desc&limit=1`))?.[0];if(idx)payload.attachments=await indexationAttachments(t,owner,idx)}
 const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(payload)}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.message||`Resend ${r.status}`);await supa(`tenant_messages?id=eq.${id}`,{method:'PATCH',body:JSON.stringify({status:'sent',sent_at:new Date().toISOString(),provider_message_id:j.id,updated_at:new Date().toISOString()})});await event(id,'sent',{provider_message_id:j.id,attachments:Boolean(payload.attachments?.length)});return res.status(200).json({ok:true,id:j.id,attachments:payload.attachments?.map(x=>x.filename)||[]})}catch(e){return res.status(400).json({error:e.message||String(e)})}};

return module.exports; })();

handlers["run-reminders"] = (() => { const module = {exports:{}}; const exports = module.exports;
const crypto=require('crypto');
const {supa,trackingUrl,replyAddress,event}=require('../lib/core');
function nextDate(iso,rec){const d=new Date(iso||Date.now());if(rec==='daily')d.setDate(d.getDate()+1);else if(rec==='weekly')d.setDate(d.getDate()+7);else if(rec==='monthly')d.setMonth(d.getMonth()+1);else if(rec==='yearly')d.setFullYear(d.getFullYear()+1);else return null;return d.toISOString()}
function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\n/g,'<br>')}
async function sendOne(m){if(!process.env.RESEND_API_KEY||!(process.env.RESEND_FROM_EMAIL||process.env.REMINDER_FROM_EMAIL))return false;const tenants=await supa(`tenants?id=eq.${m.tenant_id}&workspace_id=eq.${m.workspace_id}&select=name,email`),t=tenants?.[0];if(!t?.email)return false;const payload={from:(process.env.RESEND_FROM_EMAIL||process.env.REMINDER_FROM_EMAIL),to:[t.email],subject:m.subject||'Message from Property Manager Pro',html:`<div style="font-family:Arial,sans-serif;line-height:1.7;color:#19324d;max-width:640px;margin:auto;background:#fff;border:1px solid #e1e8f0;border-radius:18px;overflow:hidden"><div style="padding:22px 28px;background:#0d3155;color:#fff"><b style="letter-spacing:.12em;font-size:11px">MANAGERENT4U</b><h2 style="margin:8px 0 0">${esc(m.subject)}</h2></div><div style="padding:28px">${esc(m.body)}</div></div><img src="${trackingUrl('open',m.tracking_token)}" width="1" height="1" alt="" style="display:none">`};const reply=replyAddress(m.tracking_token);if(m.reply_mode==='allow'&&reply)payload.reply_to=reply;const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(payload)});const j=await r.json().catch(()=>({}));if(!r.ok)return false;await supa(`tenant_messages?id=eq.${m.id}`,{method:'PATCH',body:JSON.stringify({status:'sent',sent_at:new Date().toISOString(),provider_message_id:j.id,updated_at:new Date().toISOString()})});await event(m.id,'sent',{provider_message_id:j.id,automated:true});return true}
function dueDay(t){const m=String(t?.stay_notes||'').match(/__MR4U_DUE_DAY:(\d{1,2})__/),n=m?Number(m[1]):1;return n>=1&&n<=28?n:1}
async function generateRentAccounts(){const now=new Date(),year=now.getUTCFullYear(),month=now.getUTCMonth()+1,day=now.getUTCDate();const tenants=await supa('tenants?active=eq.true&select=id,workspace_id,tenancy_type,rent,base_rent,additional_costs,stay_notes');const existing=await supa(`payments?year=eq.${year}&month=eq.${month}&select=tenant_id`);const seen=new Set((existing||[]).map(x=>String(x.tenant_id)));let generated=0;for(const t of tenants||[]){if(String(t.tenancy_type||'long_term')==='short_stay'||seen.has(String(t.id))||day<dueDay(t))continue;const expected=Number(t.rent||0)||Number(t.base_rent||0)+Number(t.additional_costs||0);try{await supa('payments',{method:'POST',body:JSON.stringify({workspace_id:t.workspace_id,tenant_id:t.id,year,month,expected_amount:expected,paid_amount:0,status:'pending'})});seen.add(String(t.id));generated++}catch(e){console.error('AUTO_RENT_ACCOUNT',t.id,e.message)}}return generated}
module.exports=async(req,res)=>{try{const auth=req.headers.authorization||'';if(process.env.CRON_SECRET&&auth!==`Bearer ${process.env.CRON_SECRET}`)return res.status(401).json({error:'Unauthorized'});const generated_accounts=await generateRentAccounts();const due=await supa(`tenant_reminders?active=eq.true&next_run_at=lte.${encodeURIComponent(new Date().toISOString())}&select=*&limit=100`);let created=0,sent=0;for(const r of due||[]){const token=crypto.randomUUID().replaceAll('-','');const rows=await supa('tenant_messages',{method:'POST',body:JSON.stringify({workspace_id:r.workspace_id,tenant_id:r.tenant_id,subject:r.title,body:r.message_body,delivery_channel:r.channel,reply_mode:r.reply_mode,status:'queued',tracking_token:token})});const m=rows?.[0];if(m){created++;if(await sendOne(m))sent++}const next=nextDate(r.next_run_at,r.recurrence);await supa(`tenant_reminders?id=eq.${r.id}`,{method:'PATCH',body:JSON.stringify({last_run_at:new Date().toISOString(),next_run_at:next,active:Boolean(next),updated_at:new Date().toISOString()})})}return res.status(200).json({ok:true,generated_accounts,created,sent})}catch(e){return res.status(400).json({error:e.message||String(e)})}}

return module.exports; })();

handlers["webhook"] = (() => { const module = {exports:{}}; const exports = module.exports;
const {supa,event,verifySvix}=require('../lib/core');
module.exports=async(req,res)=>{try{const raw=typeof req.body==='string'?req.body:JSON.stringify(req.body||{});if(!verifySvix(raw,req.headers))return res.status(401).json({error:'Invalid webhook signature'});const body=typeof req.body==='string'?JSON.parse(req.body):req.body||{},type=body.type||'';
if(type==='email.received'){const to=body.data?.to||body.data?.recipients||[],list=Array.isArray(to)?to:[to],addr=list.map(x=>typeof x==='string'?x:x?.email||'').find(x=>/reply\+[^@]+@/i.test(x)),token=(addr?.match(/reply\+([^@]+)@/i)||[])[1];if(!token)return res.status(200).json({ok:true});const rows=await supa(`tenant_messages?tracking_token=eq.${encodeURIComponent(token)}&select=id`),m=rows?.[0];if(!m)return res.status(200).json({ok:true});const text=body.data?.text||body.data?.subject||'Tenant replied';await supa(`tenant_messages?id=eq.${m.id}`,{method:'PATCH',body:JSON.stringify({status:'replied',last_reply_text:String(text).slice(0,10000),updated_at:new Date().toISOString()})});await event(m.id,'replied',{provider_event_id:body.id||null});return res.status(200).json({ok:true})}
const providerId=body.data?.email_id||body.data?.id||'';if(!providerId)return res.status(200).json({ok:true});const rows=await supa(`tenant_messages?provider_message_id=eq.${encodeURIComponent(providerId)}&select=id`),m=rows?.[0];if(!m)return res.status(200).json({ok:true});const map={'email.delivered':'delivered','email.opened':'opened','email.bounced':'bounced','email.failed':'failed'},evt=map[type];if(evt){await event(m.id,evt,{provider_event_id:body.id||null});const status=evt==='delivered'?'delivered':evt==='bounced'||evt==='failed'?'failed':null;if(status)await supa(`tenant_messages?id=eq.${m.id}`,{method:'PATCH',body:JSON.stringify({status,updated_at:new Date().toISOString()})})}return res.status(200).json({ok:true})}catch(e){return res.status(400).json({error:e.message||String(e)})}}

return module.exports; })();

handlers["tracking"] = (() => { const module = {exports:{}}; const exports = module.exports;
const {supa,event}=require('../lib/core');
const pixel=Buffer.from('R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==','base64');
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
module.exports=async(req,res)=>{
  const mode=String(req.query?.mode||'');
  const token=String(req.query?.token||'');
  if(mode==='open'){
    try{if(token){const rows=await supa(`tenant_messages?tracking_token=eq.${encodeURIComponent(token)}&select=id`);if(rows?.[0])await event(rows[0].id,'opened',{user_agent:req.headers['user-agent']||''})}}catch{}
    res.setHeader('Content-Type','image/gif');res.setHeader('Cache-Control','no-store');return res.status(200).send(pixel);
  }
  if(mode==='copy'){
    try{const rows=await supa(`tenant_messages?tracking_token=eq.${encodeURIComponent(token)}&select=id,tenant_id`);const m=rows?.[0];if(!m)return res.status(404).send('Message not found');const tenants=await supa(`tenants?id=eq.${m.tenant_id}&select=payment_reference`);const ref=String(tenants?.[0]?.payment_reference||'');res.setHeader('Content-Type','text/html; charset=utf-8');return res.status(200).send(`<!doctype html><meta name="viewport" content="width=device-width"><title>Copy payment reference</title><body style="margin:0;background:#f4f7fb;font-family:Arial,sans-serif;color:#17324f"><main style="max-width:520px;margin:60px auto;background:white;border:1px solid #dde6ef;border-radius:18px;padding:30px;box-shadow:0 18px 50px rgba(28,52,83,.08)"><div style="font-size:12px;font-weight:800;color:#1764be">MANAGERENT4U</div><h1 style="font-size:24px">Payment reference</h1><div id="ref" style="font:800 20px Consolas,monospace;white-space:nowrap;border:1px solid #d6e2ef;background:#f7faff;border-radius:12px;padding:16px;margin:18px 0">${esc(ref)}</div><button id="copy" style="border:0;border-radius:10px;background:#1768c7;color:white;padding:12px 18px;font-weight:800;cursor:pointer">⧉ Copy reference</button><span id="ok" style="margin-left:10px;color:#16814b;font-weight:700"></span><script>document.getElementById('copy').onclick=async()=>{try{await navigator.clipboard.writeText(${JSON.stringify(ref)});document.getElementById('ok').textContent='Copied ✓'}catch(e){const r=document.createRange();r.selectNode(document.getElementById('ref'));getSelection().removeAllRanges();getSelection().addRange(r);document.getElementById('ok').textContent='Selected — press Ctrl+C'}}</script></main></body>`)}catch(e){return res.status(500).send(esc(e.message||e))}
  }
  if(mode==='view'){
    try{const rows=await supa(`tenant_messages?tracking_token=eq.${encodeURIComponent(token)}&select=*`);const m=rows?.[0];if(!m)return res.status(404).send('Message not found');await event(m.id,'link_viewed',{user_agent:req.headers['user-agent']||''});const tenants=await supa(`tenants?id=eq.${m.tenant_id}&select=name`);const name=tenants?.[0]?.name||'Tenant';res.setHeader('Content-Type','text/html; charset=utf-8');return res.status(200).send(`<!doctype html><meta name="viewport" content="width=device-width"><title>${esc(m.subject)}</title><body style="margin:0;background:#f4f7fb;font-family:Arial,sans-serif;color:#17324f"><main style="max-width:680px;margin:40px auto;background:white;border:1px solid #dde6ef;border-radius:18px;padding:32px;box-shadow:0 18px 50px rgba(28,52,83,.08)"><div style="font-size:12px;font-weight:800;color:#1764be">MANAGERENT4U</div><h1 style="font-size:26px">${esc(m.subject||'Message')}</h1><p style="color:#61758d">For ${esc(name)}</p><div style="white-space:pre-wrap;line-height:1.7;font-size:15px">${esc(m.body)}</div><div style="margin-top:28px;padding-top:18px;border-top:1px solid #edf1f5;color:#8190a1;font-size:12px">This secure page records that the message link was viewed.</div></main></body>`)}catch(e){return res.status(500).send(esc(e.message||e))}
  }
  return res.status(400).json({error:'Invalid tracking mode'});
};

return module.exports; })();

module.exports = async (req,res) => {
  res.setHeader('Access-Control-Allow-Origin','*');
  res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');
  res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization');
  if(req.method==='OPTIONS') return res.status(204).end();
  const action = String(req.query.action || '').trim();
  const h = handlers[action];
  if(!h) return res.status(404).json({error:'Unknown messages action'});
  return h(req,res);
};
