'use strict';
const handlers = {};

handlers["create"] = (() => { const module = {exports:{}}; const exports = module.exports;
const crypto=require('crypto');
const {supa,requireUser}=require('../lib/core');
module.exports=async(req,res)=>{res.setHeader('Cache-Control','no-store');if(req.method!=='POST')return res.status(405).json({error:'POST required'});try{
  const user=await requireUser(req);
  const prof=(await supa(`user_profiles?user_id=eq.${encodeURIComponent(user.id)}&select=active_workspace_id`))?.[0];
  const workspaceId=prof?.active_workspace_id;if(!workspaceId)throw new Error('No active workspace');
  const tenantId=Number(req.body?.tenant_id);if(!tenantId)throw new Error('Tenant is required');
  const tenant=(await supa(`tenants?id=eq.${tenantId}&workspace_id=eq.${workspaceId}&select=id`))?.[0];if(!tenant)throw new Error('Tenant not found in this workspace');
  const allowedStatus=new Set(['draft','scheduled','queued']);const requested=String(req.body?.status||'draft').toLowerCase();const status=allowedStatus.has(requested)?requested:'draft';
  const token=String(req.body?.tracking_token||crypto.randomUUID().replaceAll('-',''));
  const payload={workspace_id:workspaceId,tenant_id:tenantId,subject:String(req.body?.subject||'Message').slice(0,500),body:String(req.body?.body||'').slice(0,30000000),reply_mode:String(req.body?.reply_mode||'allow'),delivery_channel:'email',status,scheduled_for:req.body?.scheduled_for||null,tracking_token:token};
  const rows=await supa('tenant_messages',{method:'POST',body:JSON.stringify(payload)}),message=rows?.[0];if(!message)throw new Error('Message could not be created');
  let reminder=null;
  const r=req.body?.reminder;
  if(r&&String(r.recurrence||'none')!=='none'){
    const rr=await supa('tenant_reminders',{method:'POST',body:JSON.stringify({workspace_id:workspaceId,tenant_id:tenantId,title:String(r.title||payload.subject).slice(0,500),message_body:String(r.message_body||req.body?.plain_body||'').slice(0,100000),reply_mode:payload.reply_mode,channel:'email',recurrence:String(r.recurrence),next_run_at:r.next_run_at||null,active:true})});reminder=rr?.[0]||null;
  }
  return res.status(200).json({ok:true,message,reminder});
}catch(e){return res.status(400).json({error:e.message||String(e)})}};
return module.exports; })();

handlers["send"] = (() => { const module = {exports:{}}; const exports = module.exports;
const crypto=require('crypto');
const {supa,requireUser,trackingUrl,replyAddress,event}=require('../lib/core');
const {PDFDocument,StandardFonts,rgb}=require('pdf-lib');
const esc=s=>String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
function storedAttachmentItems(body){const m=String(body||'').match(/\n?__MR4U_ATTACHMENTS:([A-Za-z0-9+/=]+)__/);if(!m)return[];try{return JSON.parse(Buffer.from(m[1],'base64').toString('utf8'))||[]}catch{return[]}}
function storedCc(body){const m=String(body||'').match(/\n?__MR4U_CC:([A-Za-z0-9+/=]+)__/);if(!m)return[];try{return (JSON.parse(Buffer.from(m[1],'base64').toString('utf8'))||[]).map(x=>String(x||'').trim()).filter(Boolean)}catch{return[]}}
function cleanStoredMessageBody(body){return String(body||'').replace(/\n?__MR4U_ATTACHMENTS:[A-Za-z0-9+/=]+__/g,'').replace(/\n?__MR4U_CC:[A-Za-z0-9+/=]+__/g,'').replace(/\n?__MR4U_RESEND_OF:[0-9]+__/g,'').trim()}
function parseCustomAttachments(body){const items=storedAttachmentItems(body),attachments=items.filter(x=>x&&x.name&&x.content).map(x=>({filename:String(x.name).replace(/[\r\n]/g,' ').slice(0,180),content:String(x.content)}));return{body:cleanStoredMessageBody(body),attachments,cc:storedCc(body),storedItems:items}}
function attachmentMime(name){return /\.pdf$/i.test(name)?'application/pdf':/\.svg$/i.test(name)?'image/svg+xml':/\.png$/i.test(name)?'image/png':/\.jpe?g$/i.test(name)?'image/jpeg':'application/octet-stream'}
function serializeStoredAttachments(items){return Buffer.from(JSON.stringify(items||[]),'utf8').toString('base64')}
const eur=n=>new Intl.NumberFormat('nl-BE',{style:'currency',currency:'EUR'}).format(Number(n||0));
function fmtDate(v,lang='en'){if(!v)return '—';try{return new Date(String(v).slice(0,10)+'T12:00:00').toLocaleDateString(lang==='nl'?'nl-BE':lang==='fr'?'fr-BE':'en-GB',{day:'2-digit',month:'long',year:'numeric'})}catch{return String(v)}}
async function ownerForTenant(t){try{let unitId=t?.unit_id||null;if(!unitId){const rel=await supa(`tenant_units?tenant_id=eq.${t.id}&select=unit_id&limit=1`);unitId=rel?.[0]?.unit_id}if(!unitId)return null;const units=await supa(`units?id=eq.${unitId}&select=building_id&limit=1`),buildingId=units?.[0]?.building_id;if(!buildingId)return null;const buildings=await supa(`buildings?id=eq.${buildingId}&select=owner_id&limit=1`),ownerId=buildings?.[0]?.owner_id;if(!ownerId)return null;return (await supa(`owners?id=eq.${ownerId}&select=name,email,phone,address,postal_code,city,country&limit=1`))?.[0]||null}catch{return null}}
function wrap(text,max=82){const words=String(text||'').split(/\s+/),lines=[];let line='';for(const w of words){if(!line){line=w;continue}if((line+' '+w).length>max){lines.push(line);line=w}else line+=' '+w}if(line)lines.push(line);return lines}
async function liveRentReference(t){
 try{
  const pays=await supa(`payments?tenant_id=eq.${t.id}&workspace_id=eq.${t.workspace_id}&select=year,month&order=year.desc,month.desc&limit=1`),p=pays?.[0]||{};
  let unitId=t?.unit_id||null;if(!unitId){const rel=await supa(`tenant_units?tenant_id=eq.${t.id}&select=unit_id&limit=1`);unitId=rel?.[0]?.unit_id}
  let unit=null,building=null;if(unitId){unit=(await supa(`units?id=eq.${unitId}&select=*&limit=1`))?.[0]||null;if(unit?.building_id)building=(await supa(`buildings?id=eq.${unit.building_id}&select=*&limit=1`))?.[0]||null}
  const buildingAddress=building?.address||[building?.street,building?.house_number,building?.postal_code,building?.city,building?.country].filter(Boolean).join(' ');
  const address=String(buildingAddress||building?.name||'').replace(/\s+/g,' ').trim();
  const months=['januari','februari','maart','april','mei','juni','juli','augustus','september','oktober','november','december'];const now=new Date(),m=Number(p.month||now.getMonth()+1),y=Number(p.year||now.getFullYear());
  return `Huur ${address||t.name||''} ${months[m-1]||m} ${y}`.replace(/\s+/g,' ').trim();
 }catch{return String(t.payment_reference||'').trim()||'-'}
}
async function indexationAttachments(t,owner,idx,prevIdx=null){if(!idx)return[];
 const lang=['en','fr','nl'].includes(t.communication_language)?t.communication_language:'en';
 const base=Number(idx.base_rent||t.base_rent||0),calc=Number(idx.calculated_rent||0),costs=Number(t.additional_costs||0),total=calc+costs,effective=idx.effective_date||idx.calculation_date||idx.contract_start_date||t.tenancy_start_date||'',previousEffective=prevIdx?.effective_date||prevIdx?.calculation_date||prevIdx?.contract_start_date||t.tenancy_start_date||'';
 const money=n=>`${Number(n||0).toLocaleString('nl-BE',{minimumFractionDigits:2,maximumFractionDigits:2})} EUR`;
 const ownerName=owner?.name||'Property Manager',paymentReference=await liveRentReference(t);
 const copy=lang==='nl'?{
  badge:'HUURINDEXATIE',title:`Uw huurprijs vanaf ${fmtDate(effective,'nl')}`,hello:`Beste ${t.name},`,
  intro:'Volgens de huurovereenkomst kan de basishuur jaarlijks worden aangepast aan de gezondheidsindex. Hieronder vindt u de berekening en het nieuwe maandbedrag.',
  what:'Wat verandert er?',cur:'Huidige basishuur',next:'Nieuwe geindexeerde basishuur',cost:'Vaste maandelijkse kosten',tot:'Nieuw maandelijks totaal',date:'Van toepassing vanaf',ref:'Gestructureerde mededeling',
  explainTitle:'Wat betekent dit voor u?',explain:'Vanaf de bovenstaande datum betaalt u het nieuwe maandelijkse totaal. De vaste kosten blijven apart van de indexatie en worden pas na de berekening bij de basishuur opgeteld.',
  source:'De berekening gebruikt de officiele gezondheidsindex van Statbel en de huurindexatieformule.',pay:'U mag de huur blijven storten op dezelfde rekening met dezelfde gestructureerde mededeling.',close:'Met vriendelijke groet',
  calcBadge:'BEREKENINGSBEWIJS',calcTitle:'Statbel indexatieberekening',period:'Periode',basic:'Basishuur',initial:'Aanvangsindex',newidx:'Nieuwe index',result:'Geindexeerde basishuur',formula:'Formule',effective:'Ingangsdatum',
  guideBadge:'UITLEG',guideTitle:'Zo werd het nieuwe bedrag opgebouwd',steps:[['1','Basishuur','De indexatie wordt uitsluitend berekend op de oorspronkelijke basishuur.'],['2','Gezondheidsindex','De aanvangsindex en de nieuwe index worden gebruikt in dezelfde officiele formule.'],['3','Indexatie','De basishuur wordt vermenigvuldigd met de nieuwe index en gedeeld door de aanvangsindex.'],['4','Vaste kosten','Vaste maandelijkse kosten worden daarna afzonderlijk toegevoegd.'],['5','Bewijs','Dit pakket bewaart de gebruikte indexen, formule, datum en het resultaat voor uw dossier.']]
 }:lang==='fr'?{
  badge:'INDEXATION DU LOYER',title:`Votre loyer a partir du ${fmtDate(effective,'fr')}`,hello:`Bonjour ${t.name},`,
  intro:"Conformement au bail, le loyer de base peut etre adapte annuellement sur la base de l'indice sante. Vous trouverez ci-dessous le calcul et le nouveau montant mensuel.",
  what:'Qu est-ce qui change ?',cur:'Loyer de base actuel',next:'Nouveau loyer de base indexe',cost:'Charges mensuelles fixes',tot:'Nouveau total mensuel',date:"Date d'application",ref:'Communication structuree',
  explainTitle:'Qu est-ce que cela signifie pour vous ?',explain:"A partir de la date indiquee ci-dessus, le nouveau total mensuel s'applique. Les charges fixes restent separees de l'indexation et sont ajoutees apres le calcul du loyer de base.",
  source:"Le calcul utilise l'indice sante officiel de Statbel et la formule d'indexation du loyer.",pay:'Veuillez continuer a payer sur le meme compte avec la meme communication structuree.',close:'Bien cordialement',
  calcBadge:'PREUVE DE CALCUL',calcTitle:'Calcul d indexation Statbel',period:'Periode',basic:'Loyer de base',initial:'Indice initial',newidx:'Nouvel indice',result:'Loyer de base indexe',formula:'Formule',effective:"Date d'effet",
  guideBadge:'EXPLICATION',guideTitle:'Comment le nouveau montant a ete calcule',steps:[['1','Loyer de base',"L'indexation est calculee uniquement sur le loyer de base d'origine."],['2','Indice sante',"L'indice initial et le nouvel indice sont utilises dans la meme formule officielle."],['3','Indexation','Le loyer de base est multiplie par le nouvel indice puis divise par l indice initial.'],['4','Charges fixes','Les charges mensuelles fixes sont ensuite ajoutees separement.'],['5','Justificatif','Ce dossier conserve les indices, la formule, la date et le resultat utilises.']]
 }:{
  badge:'ANNUAL RENT INDEXATION',title:`Your rent from ${fmtDate(effective,'en')}`,hello:`Dear ${t.name},`,
  intro:'Under the tenancy agreement, the basic rent may be adjusted annually using the health index. This letter explains the calculation and the new monthly amount in a clear way.',
  what:'What is changing?',cur:'Current basic rent',next:'New indexed basic rent',cost:'Fixed monthly costs',tot:'New monthly total',date:'Effective from',ref:'Payment reference',
  explainTitle:'What this means for you',explain:'From the effective date above, the new monthly total applies. Fixed monthly costs remain separate from the indexation calculation and are added only after the new basic rent has been calculated.',
  source:'The calculation uses the official Statbel health index and the standard rent-indexation formula.',pay:'Please continue paying to the usual bank account using the same payment reference.',close:'Kind regards',
  calcBadge:'CALCULATION EVIDENCE',calcTitle:'Statbel rent indexation calculation',period:'Package period',basic:'Basic rent',initial:'Initial health index',newidx:'New health index',result:'Indexed basic rent',formula:'Formula',effective:'Effective date',
  guideBadge:'EXPLANATION',guideTitle:'How the new amount was calculated',steps:[['1','Basic rent','Indexation is calculated only on the original/basic rent.'],['2','Health index','The initial health index and the new health index are used in the same official formula.'],['3','Indexation','The basic rent is multiplied by the new index and divided by the initial index.'],['4','Fixed costs','Fixed monthly costs are then added separately after the indexed basic rent is calculated.'],['5','Evidence','This package keeps the indexes, formula, effective date and result together for your records.']]
 };
 const pdf=await PDFDocument.create(),font=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold);
 function pdfSafe(v){let s=String(v??'').replace(/€/g,'EUR ').replace(/→/g,' to ').replace(/←/g,' from ').replace(/↔/g,' - ').replace(/[•●]/g,'-').replace(/[“”]/g,'\"').replace(/[‘’]/g,"'").replace(/…/g,'...').replace(/[–—]/g,'-');return Array.from(s).map(ch=>{const c=ch.charCodeAt(0);return(c===9||c===10||c===13||(c>=32&&c<=126)||(c>=160&&c<=255))?ch:'?'}).join('')}
 function page(){return pdf.addPage([595.28,841.89])}
 const C={navy:rgb(.045,.16,.30),blue:rgb(.08,.39,.86),blue2:rgb(.91,.95,1),ink:rgb(.08,.16,.27),muted:rgb(.38,.46,.56),line:rgb(.87,.91,.95),soft:rgb(.96,.98,1),green:rgb(.02,.48,.31),greenSoft:rgb(.91,.98,.95),orange:rgb(.96,.46,.08),orangeSoft:rgb(1,.96,.91),white:rgb(1,1,1)};
 function txt(pg,text,x,y,size=11,f=font,color=C.ink){pg.drawText(pdfSafe(text),{x,y,size,font:f,color});return y}
 function linesFor(text,max=75){return wrap(pdfSafe(text),max)}
 function para(pg,text,x,y,max=75,size=10.5,leading=16,color=C.ink){for(const line of linesFor(text,max)){txt(pg,line,x,y,size,font,color);y-=leading}return y}
 function box(pg,x,y,w,h,fill=C.white,border=C.line,bw=1){pg.drawRectangle({x,y,width:w,height:h,color:fill,borderColor:border,borderWidth:bw})}
 function pill(pg,label,x,y,w,fill=C.blue2,color=C.blue){box(pg,x,y,w,22,fill,fill,0);txt(pg,label,x+10,y+7,8,bold,color)}
 function pageTop(pg,badge,title,subtitle){pill(pg,badge,48,777,160);txt(pg,title,48,735,25,bold,C.navy);if(subtitle)txt(pg,subtitle,48,713,10,font,C.muted);pg.drawLine({start:{x:48,y:695},end:{x:547,y:695},thickness:1,color:C.line})}
 function footer(pg,n){pg.drawLine({start:{x:48,y:42},end:{x:547,y:42},thickness:1,color:C.line});txt(pg,'ManageRent4U',48,24,8,bold,C.muted);txt(pg,`Indexation package  •  ${n}/3`,445,24,8,font,C.muted)}
 let pg=page();pageTop(pg,copy.badge,copy.title,fmtDate(new Date().toISOString().slice(0,10),lang));let y=662;
 y=para(pg,copy.hello,48,y,72,11.5,18,C.ink)-8;y=para(pg,copy.intro,48,y,76,11,17,C.ink)-18;
 txt(pg,copy.what,48,y,14,bold,C.navy);y-=22;
 const cardY=y-118;box(pg,48,cardY,499,118,C.soft,C.line,1);
 const cols=[[copy.cur,money(base),48],[copy.next,money(calc),300]];for(const [lab,val,x] of cols){txt(pg,lab,x+16,cardY+84,8,bold,C.muted);txt(pg,val,x+16,cardY+54,17,bold,lab===copy.next?C.green:C.navy)}
 pg.drawLine({start:{x:284,y:cardY+18},end:{x:284,y:cardY+100},thickness:1,color:C.line});
 if(costs){txt(pg,copy.cost,64,cardY+24,8,bold,C.muted);txt(pg,money(costs),184,cardY+24,10,bold,C.ink);txt(pg,copy.tot,316,cardY+24,8,bold,C.muted);txt(pg,money(total),431,cardY+24,10,bold,C.blue)}
 y=cardY-26;box(pg,48,y-88,499,88,C.blue2,C.blue2,0);txt(pg,copy.date,64,y-24,8,bold,C.blue);txt(pg,fmtDate(effective,lang),64,y-48,13,bold,C.navy);txt(pg,copy.ref,286,y-24,8,bold,C.blue);let refY=y-46;for(const line of wrap(paymentReference||'-',40).slice(0,3)){txt(pg,line,286,refY,9.5,bold,C.navy);refY-=13}y-=114;
 txt(pg,copy.explainTitle,48,y,13,bold,C.navy);y-=22;y=para(pg,copy.explain,48,y,78,10.5,16,C.ink)-10;y=para(pg,copy.source,48,y,78,9.5,15,C.muted)-2;y=para(pg,copy.pay,48,y,78,10.5,16,C.ink)-18;
 txt(pg,copy.close+',',48,y,10.5,font,C.ink);y-=18;txt(pg,ownerName,48,y,11,bold,C.navy);footer(pg,1);

 pg=page();pageTop(pg,copy.calcBadge,copy.calcTitle,`${copy.period}: ${fmtDate(previousEffective,lang)} - ${fmtDate(effective,lang)}`);y=648;
 const ev=[[copy.basic,money(base)],[copy.initial,String(idx.initial_index||'-')],[copy.newidx,String(idx.new_index||'-')],[copy.result,money(calc)],[copy.effective,fmtDate(effective,lang)]];
 const positions=[[48,566],[302,566],[48,486],[302,486],[48,406]];ev.forEach(([lab,val],i)=>{const [x,yy]=positions[i];box(pg,x,yy,245,64,C.soft,C.line,1);txt(pg,lab,x+14,yy+40,8,bold,C.muted);txt(pg,val,x+14,yy+17,13,bold,i===3?C.green:C.navy)});
 box(pg,48,286,499,92,C.navy,C.navy,0);txt(pg,copy.formula,66,350,8,bold,rgb(.70,.80,.92));txt(pg,`${base.toFixed(2)} x ${idx.new_index||'-'} / ${idx.initial_index||'-'} = ${calc.toFixed(2)}`,66,316,18,bold,C.white);
 box(pg,48,176,499,82,C.greenSoft,C.greenSoft,0);txt(pg,copy.result,66,228,8,bold,C.green);txt(pg,money(calc),66,194,22,bold,C.green);txt(pg,copy.tot,320,228,8,bold,C.muted);txt(pg,money(total),320,198,16,bold,C.navy);
 txt(pg,'STATBEL',48,136,9,bold,C.blue);y=para(pg,'Source: official Statbel health-index data and the official rent calculator. ManageRent4U stores the calculation inputs and result together with the tenant notice.',48,118,82,9,14,C.muted);footer(pg,2);

 pg=page();pageTop(pg,copy.guideBadge,copy.guideTitle,copy.title);y=646;
 copy.steps.forEach(([num,h,d],i)=>{const hgt=82;box(pg,48,y-hgt+6,499,hgt,i===0?C.blue2:C.white,C.line,1);box(pg,62,y-50,34,34,i===0?C.blue:C.soft,i===0?C.blue:C.line,1);txt(pg,num,74,y-39,11,bold,i===0?C.white:C.navy);txt(pg,h,112,y-25,12,bold,C.navy);para(pg,d,112,y-46,66,9.5,14,C.muted);y-=94});
 box(pg,48,90,499,74,C.orangeSoft,C.orangeSoft,0);txt(pg,copy.tot,64,138,8,bold,C.orange);txt(pg,money(total),64,108,18,bold,C.navy);txt(pg,copy.date,330,138,8,bold,C.orange);txt(pg,fmtDate(effective,lang),330,110,11,bold,C.navy);footer(pg,3);
 const bytes=await pdf.save();
 const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="760"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#0d3155"/><stop offset="1" stop-color="#1768df"/></linearGradient></defs><rect width="1200" height="760" fill="#f4f7fb"/><rect x="62" y="54" width="1076" height="652" rx="30" fill="white" stroke="#dbe5ef"/><rect x="92" y="84" width="1016" height="92" rx="22" fill="url(#g)"/><text x="126" y="120" font-family="Arial" font-size="17" font-weight="700" fill="#bcd5ff">STATBEL CALCULATION EVIDENCE</text><text x="126" y="154" font-family="Arial" font-size="31" font-weight="700" fill="white">Rent indexation calculation</text><g font-family="Arial"><text x="116" y="236" font-size="17" fill="#60738a">Basic rent</text><text x="490" y="236" text-anchor="end" font-size="23" font-weight="700" fill="#142d4d">${esc(money(base))}</text><text x="624" y="236" font-size="17" fill="#60738a">Effective from</text><text x="1076" y="236" text-anchor="end" font-size="23" font-weight="700" fill="#142d4d">${esc(fmtDate(effective,lang))}</text><rect x="104" y="272" width="470" height="102" rx="18" fill="#f5f8fc" stroke="#dbe5ef"/><text x="132" y="310" font-size="16" fill="#60738a">Initial health index</text><text x="132" y="349" font-size="29" font-weight="700" fill="#142d4d">${esc(idx.initial_index||'-')}</text><rect x="626" y="272" width="470" height="102" rx="18" fill="#f5f8fc" stroke="#dbe5ef"/><text x="654" y="310" font-size="16" fill="#60738a">New health index</text><text x="654" y="349" font-size="29" font-weight="700" fill="#142d4d">${esc(idx.new_index||'-')}</text><rect x="104" y="402" width="992" height="110" rx="18" fill="#0d3155"/><text x="132" y="438" font-size="15" font-weight="700" fill="#bcd5ff">FORMULA</text><text x="600" y="484" text-anchor="middle" font-family="monospace" font-size="28" font-weight="700" fill="white">${base.toFixed(2)} x ${esc(idx.new_index||'-')} / ${esc(idx.initial_index||'-')} = ${calc.toFixed(2)}</text><rect x="104" y="542" width="992" height="116" rx="18" fill="#eaf8f1"/><text x="132" y="580" font-size="16" font-weight="700" fill="#087a50">INDEXED BASIC RENT</text><text x="132" y="626" font-size="34" font-weight="700" fill="#087a50">${esc(money(calc))}</text><text x="1060" y="626" text-anchor="end" font-size="16" fill="#60738a">Official Statbel values used by ManageRent4U</text></g></svg>`;
 const safeFrom=String(previousEffective||'start').slice(0,10),safeTo=String(effective||'current').slice(0,10);
 return[{filename:`indexation-package-${safeFrom}-to-${safeTo}.pdf`,content:Buffer.from(bytes).toString('base64')},{filename:`statbel-evidence-${safeTo}.svg`,content:Buffer.from(svg).toString('base64')}]
}
module.exports=async(req,res)=>{res.setHeader('Cache-Control','no-store');if(req.method!=='POST')return res.status(405).json({error:'POST required'});try{const user=await requireUser(req);const prof=(await supa(`user_profiles?user_id=eq.${encodeURIComponent(user.id)}&select=active_workspace_id`))?.[0];if(!prof?.active_workspace_id)throw new Error('No active workspace');if(!process.env.RESEND_API_KEY)throw new Error('Email sender is not configured.');const from=process.env.RESEND_FROM_EMAIL||process.env.REMINDER_FROM_EMAIL;if(!from)throw new Error('Email sender is not configured.');let id=Number(req.body?.message_id);const rows=await supa(`tenant_messages?id=eq.${id}&workspace_id=eq.${prof.active_workspace_id}&select=*`);let m=rows?.[0];if(!m)throw new Error('Message not found');if(req.body?.copy_on_send&&!req.body?.preview_only){const originalId=id;const resendMarker=`\n__MR4U_RESEND_OF:${originalId}__`;const cloneRows=await supa('tenant_messages',{method:'POST',body:JSON.stringify({workspace_id:m.workspace_id,tenant_id:m.tenant_id,subject:m.subject,body:`${m.body||''}${resendMarker}`,reply_mode:m.reply_mode||'allow',delivery_channel:m.delivery_channel||'email',status:'queued',scheduled_for:null,tracking_token:crypto.randomUUID().replaceAll('-','')})});const clone=cloneRows?.[0];if(!clone)throw new Error('Could not create resend copy');m=clone;id=Number(clone.id)}const tenants=await supa(`tenants?id=eq.${m.tenant_id}&workspace_id=eq.${prof.active_workspace_id}&select=*`),t=tenants?.[0];if(!t?.email)throw new Error('Tenant has no email address');const open=trackingUrl('open',m.tracking_token),owner=await ownerForTenant(t),ownerName=String(owner?.name||'').trim(),parsed=parseCustomAttachments(m.body),rawBody=String(parsed.body||'').replace(/(Thank you,|Merci,|Dank u,|Kind regards,|Bien cordialement,|Met vriendelijke groeten?,)\s*\nManageRent4U\s*$/i,(x,g)=>`${g}\n${ownerName||'Property Manager'}`),body=esc(rawBody).replace(/\n/g,'<br>'),subject=esc(m.subject||'ManageRent4U message'),reference=String(t.payment_reference||'').trim();
 const html=`<!doctype html><html><body style="margin:0;background:#f3f6fa;font-family:Arial,Helvetica,sans-serif;color:#172b4d"><div style="padding:38px 14px"><div style="max-width:680px;margin:auto;background:#fff;border:1px solid #e1e8f0;border-radius:20px;overflow:hidden;box-shadow:0 16px 44px rgba(15,35,65,.08)"><div style="padding:24px 30px;background:linear-gradient(135deg,#092846,#123e6c);color:#fff"><div style="font-size:11px;letter-spacing:1.7px;font-weight:800;opacity:.78">MANAGERENT4U</div><div style="font-size:25px;line-height:1.25;font-weight:800;margin-top:9px">${subject}</div></div><div style="padding:30px;font-size:15px;line-height:1.72;color:#29435f"><div>${body}</div></div><div style="padding:18px 30px;border-top:1px solid #edf1f5;color:#8a98a8;font-size:11px;background:#fbfcfe">ManageRent4U · Secure property communication</div></div></div><img src="${open}" width="1" height="1" alt="" style="display:none"></body></html>`;
 const ccOverride=Array.isArray(req.body?.cc)?req.body.cc.map(x=>String(x||'').trim()).filter(x=>/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(x)):null;const effectiveCc=ccOverride!==null?ccOverride:(parsed.cc||[]);const payload={from,to:[t.email],subject:m.subject||'ManageRent4U message',html};if(parsed.attachments.length)payload.attachments=[...parsed.attachments];if(effectiveCc.length)payload.cc=[...new Set(effectiveCc.filter(x=>x&&x!==t.email))];if(ccOverride!==null){const ccMarker=effectiveCc.length?`\n__MR4U_CC:${Buffer.from(JSON.stringify(effectiveCc),'utf8').toString('base64')}__`:'';const attachmentMarker=parsed.storedItems?.length?`\n__MR4U_ATTACHMENTS:${serializeStoredAttachments(parsed.storedItems)}__`:'';const updatedBody=`${cleanStoredMessageBody(m.body)}${attachmentMarker}${ccMarker}`.trim();await supa(`tenant_messages?id=eq.${id}`,{method:'PATCH',body:JSON.stringify({body:updatedBody,updated_at:new Date().toISOString()})});m.body=updatedBody;}const reply=replyAddress(m.tracking_token);if(m.reply_mode==='allow'&&reply)payload.reply_to=reply;const context=(String(m.subject||'')+' '+rawBody).toLowerCase();let generated=[];const generatedIndexFile=/indexation-package|statbel-evidence|rent-indexation-notice|statbel-calculation/i;if(req.body?.copy_on_send){payload.attachments=(payload.attachments||[]).filter(a=>!generatedIndexFile.test(a.filename||''));}const hasSavedIndexPackage=!req.body?.copy_on_send&&!req.body?.preview_only&&(parsed.attachments||[]).some(a=>generatedIndexFile.test(a.filename||''));if(/indexation|indexatie|indexation annuelle|huurindexatie/.test(context)&&!hasSavedIndexPackage){const idxs=await supa(`tenant_indexations?tenant_id=eq.${t.id}&workspace_id=eq.${prof.active_workspace_id}&select=*&order=calculation_date.desc,created_at.desc&limit=2`),idx=idxs?.[0],prevIdx=idxs?.[1]||null;if(idx){generated=await indexationAttachments(t,owner,idx,prevIdx);payload.attachments=[...(payload.attachments||[]),...generated];const generatedStored=generated.map(a=>({name:a.filename,type:attachmentMime(a.filename),size:Buffer.from(a.content,'base64').length,content:a.content}));const merged=[...(parsed.storedItems||[]).filter(a=>!generatedIndexFile.test(a.name||'')),...generatedStored];const ccMarker=effectiveCc?.length?`
__MR4U_CC:${Buffer.from(JSON.stringify(effectiveCc),'utf8').toString('base64')}__`:'';const storedBody=`${cleanStoredMessageBody(m.body)}
__MR4U_ATTACHMENTS:${serializeStoredAttachments(merged)}__${ccMarker}`.trim();await supa(`tenant_messages?id=eq.${id}`,{method:'PATCH',body:JSON.stringify({body:storedBody,updated_at:new Date().toISOString()})});m.body=storedBody}}
 if(req.body?.preview_only)return res.status(200).json({ok:true,preview:true,attachments:(payload.attachments||[]).map(x=>x.filename),cc:payload.cc||[]});
 const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(payload)}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.message||`Resend ${r.status}`);await supa(`tenant_messages?id=eq.${id}`,{method:'PATCH',body:JSON.stringify({status:'sent',sent_at:new Date().toISOString(),provider_message_id:j.id,updated_at:new Date().toISOString()})});await event(id,'sent',{provider_message_id:j.id,attachments:Boolean(payload.attachments?.length),cc:payload.cc||[]});return res.status(200).json({ok:true,id:j.id,message_id:id,attachments:payload.attachments?.map(x=>x.filename)||[],cc:payload.cc||[]})}catch(e){return res.status(400).json({error:e.message||String(e)})}};

return module.exports; })();

handlers["run-reminders"] = (() => { const module = {exports:{}}; const exports = module.exports;
const crypto=require('crypto');
const {supa,trackingUrl,replyAddress,event}=require('../lib/core');
function nextDate(iso,rec){const d=new Date(iso||Date.now());if(rec==='daily')d.setDate(d.getDate()+1);else if(rec==='weekly')d.setDate(d.getDate()+7);else if(rec==='monthly')d.setMonth(d.getMonth()+1);else if(rec==='yearly')d.setFullYear(d.getFullYear()+1);else return null;return d.toISOString()}
function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\n/g,'<br>')}
async function sendOne(m){if(!process.env.RESEND_API_KEY||!(process.env.RESEND_FROM_EMAIL||process.env.REMINDER_FROM_EMAIL))return false;const tenants=await supa(`tenants?id=eq.${m.tenant_id}&workspace_id=eq.${m.workspace_id}&select=name,email`),t=tenants?.[0];if(!t?.email)return false;const payload={from:(process.env.RESEND_FROM_EMAIL||process.env.REMINDER_FROM_EMAIL),to:[t.email],subject:m.subject||'Message from Property Manager Pro',html:`<div style="font-family:Arial,sans-serif;line-height:1.7;color:#19324d;max-width:640px;margin:auto;background:#fff;border:1px solid #e1e8f0;border-radius:18px;overflow:hidden"><div style="padding:22px 28px;background:#0d3155;color:#fff"><b style="letter-spacing:.12em;font-size:11px">MANAGERENT4U</b><h2 style="margin:8px 0 0">${esc(m.subject)}</h2></div><div style="padding:28px">${esc(m.body)}</div></div><img src="${trackingUrl('open',m.tracking_token)}" width="1" height="1" alt="" style="display:none">`};const reply=replyAddress(m.tracking_token);if(m.reply_mode==='allow'&&reply)payload.reply_to=reply;const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(payload)});const j=await r.json().catch(()=>({}));if(!r.ok)return false;await supa(`tenant_messages?id=eq.${m.id}`,{method:'PATCH',body:JSON.stringify({status:'sent',sent_at:new Date().toISOString(),provider_message_id:j.id,updated_at:new Date().toISOString()})});await event(m.id,'sent',{provider_message_id:j.id,automated:true});return true}
function dueDay(t){const m=String(t?.stay_notes||'').match(/__MR4U_DUE_DAY:(\d{1,2})__/),n=m?Number(m[1]):1;return n>=1&&n<=28?n:1}
async function generateRentAccounts(){const now=new Date(),year=now.getUTCFullYear(),month=now.getUTCMonth()+1,day=now.getUTCDate();const tenants=await supa('tenants?active=eq.true&select=id,workspace_id,tenancy_type,current_rent,rent,base_rent,additional_costs,stay_notes');const existing=await supa(`payments?year=eq.${year}&month=eq.${month}&select=tenant_id`);const seen=new Set((existing||[]).map(x=>String(x.tenant_id)));let generated=0;for(const t of tenants||[]){if(String(t.tenancy_type||'long_term')==='short_stay'||seen.has(String(t.id))||day<dueDay(t))continue;const expected=Number(t.current_rent??t.rent??t.base_rent??0)+Number(t.additional_costs||0);try{await supa('payments',{method:'POST',body:JSON.stringify({workspace_id:t.workspace_id,tenant_id:t.id,year,month,expected_amount:expected,paid_amount:0,status:'pending'})});seen.add(String(t.id));generated++}catch(e){console.error('AUTO_RENT_ACCOUNT',t.id,e.message)}}return generated}
module.exports=async(req,res)=>{try{const auth=req.headers.authorization||'';if(process.env.CRON_SECRET&&auth!==`Bearer ${process.env.CRON_SECRET}`)return res.status(401).json({error:'Unauthorized'});const generated_accounts=await generateRentAccounts();const due=await supa(`tenant_reminders?active=eq.true&next_run_at=lte.${encodeURIComponent(new Date().toISOString())}&select=*&limit=100`);let created=0,sent=0;for(const r of due||[]){const token=crypto.randomUUID().replaceAll('-','');const rows=await supa('tenant_messages',{method:'POST',body:JSON.stringify({workspace_id:r.workspace_id,tenant_id:r.tenant_id,subject:r.title,body:r.message_body,delivery_channel:r.channel,reply_mode:r.reply_mode,status:'queued',tracking_token:token})});const m=rows?.[0];if(m){created++;if(await sendOne(m))sent++}const next=nextDate(r.next_run_at,r.recurrence);await supa(`tenant_reminders?id=eq.${r.id}`,{method:'PATCH',body:JSON.stringify({last_run_at:new Date().toISOString(),next_run_at:next,active:Boolean(next),updated_at:new Date().toISOString()})})}return res.status(200).json({ok:true,generated_accounts,created,sent})}catch(e){return res.status(400).json({error:e.message||String(e)})}}

return module.exports; })();

handlers["webhook"] = (() => { const module = {exports:{}}; const exports = module.exports;
const {supa,event,verifySvix}=require('../lib/core');
module.exports=async(req,res)=>{try{const raw=typeof req.body==='string'?req.body:JSON.stringify(req.body||{});if(!verifySvix(raw,req.headers))return res.status(401).json({error:'Invalid webhook signature'});const body=typeof req.body==='string'?JSON.parse(req.body):req.body||{},type=body.type||'';
if(type==='email.received'){const to=body.data?.to||body.data?.recipients||[],list=Array.isArray(to)?to:[to],addr=list.map(x=>typeof x==='string'?x:x?.email||'').find(x=>/reply\+[^@]+@/i.test(x)),token=(addr?.match(/reply\+([^@]+)@/i)||[])[1];if(!token)return res.status(200).json({ok:true});const rows=await supa(`tenant_messages?tracking_token=eq.${encodeURIComponent(token)}&select=id`),m=rows?.[0];if(!m)return res.status(200).json({ok:true});const text=body.data?.text||body.data?.subject||'Tenant replied';await supa(`tenant_messages?id=eq.${m.id}`,{method:'PATCH',body:JSON.stringify({status:'replied',last_reply_text:String(text).slice(0,10000),updated_at:new Date().toISOString()})});await event(m.id,'replied',{provider_event_id:body.id||null});return res.status(200).json({ok:true})}
const providerId=body.data?.email_id||body.data?.id||'';if(!providerId)return res.status(200).json({ok:true});const rows=await supa(`tenant_messages?provider_message_id=eq.${encodeURIComponent(providerId)}&select=id`),m=rows?.[0];if(!m)return res.status(200).json({ok:true});const map={'email.delivered':'delivered','email.opened':'opened','email.bounced':'bounced','email.failed':'failed'},evt=map[type];if(evt){const rawRecipients=body.data?.to||body.data?.recipients||body.data?.email?.to||[],to=(Array.isArray(rawRecipients)?rawRecipients:[rawRecipients]).map(x=>typeof x==='string'?x:(x?.email||x?.address||'')).filter(Boolean);await event(m.id,evt,{provider_event_id:body.id||null,to,recipient:to.length===1?to[0]:null});const status=evt==='delivered'?'delivered':evt==='bounced'||evt==='failed'?'failed':null;if(status)await supa(`tenant_messages?id=eq.${m.id}`,{method:'PATCH',body:JSON.stringify({status,updated_at:new Date().toISOString()})})}return res.status(200).json({ok:true})}catch(e){return res.status(400).json({error:e.message||String(e)})}}

return module.exports; })();

handlers["tracking"] = (() => { const module = {exports:{}}; const exports = module.exports;
const {supa,event}=require('../lib/core');
const pixel=Buffer.from('R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==','base64');
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
module.exports=async(req,res)=>{
  const mode=String(req.query?.mode||'');
  const token=String(req.query?.token||'');
  if(mode==='open'){
    try{if(token){const rows=await supa(`tenant_messages?tracking_token=eq.${encodeURIComponent(token)}&select=id`);if(rows?.[0])await event(rows[0].id,'opened',{user_agent:req.headers['user-agent']||''})}}catch{}
    res.setHeader('Content-Type','image/gif');res.setHeader('Cache-Control','no-store');return res.status(200).send(pixel);
  }
  if(mode==='copy'){
    try{const rows=await supa(`tenant_messages?tracking_token=eq.${encodeURIComponent(token)}&select=id,tenant_id`);const m=rows?.[0];if(!m)return res.status(404).send('Message not found');const tenants=await supa(`tenants?id=eq.${m.tenant_id}&select=payment_reference`);const ref=String(tenants?.[0]?.payment_reference||'');res.setHeader('Content-Type','text/html; charset=utf-8');return res.status(200).send(`<!doctype html><meta name="viewport" content="width=device-width"><title>Copy payment reference</title><body style="margin:0;background:#f4f7fb;font-family:Arial,sans-serif;color:#17324f"><main style="max-width:520px;margin:60px auto;background:white;border:1px solid #dde6ef;border-radius:18px;padding:30px;box-shadow:0 18px 50px rgba(28,52,83,.08)"><div style="font-size:12px;font-weight:800;color:#1764be">MANAGERENT4U</div><h1 style="font-size:24px">Payment reference</h1><div id="ref" style="font:800 20px Consolas,monospace;white-space:nowrap;border:1px solid #d6e2ef;background:#f7faff;border-radius:12px;padding:16px;margin:18px 0">${esc(ref)}</div><button id="copy" style="border:0;border-radius:10px;background:#1768c7;color:white;padding:12px 18px;font-weight:800;cursor:pointer">⧉ Copy reference</button><span id="ok" style="margin-left:10px;color:#16814b;font-weight:700"></span><script>document.getElementById('copy').onclick=async()=>{try{await navigator.clipboard.writeText(${JSON.stringify(ref)});document.getElementById('ok').textContent='Copied ✓'}catch(e){const r=document.createRange();r.selectNode(document.getElementById('ref'));getSelection().removeAllRanges();getSelection().addRange(r);document.getElementById('ok').textContent='Selected — press Ctrl+C'}}</script></main></body>`)}catch(e){return res.status(500).send(esc(e.message||e))}
  }
  if(mode==='view'){
    try{const rows=await supa(`tenant_messages?tracking_token=eq.${encodeURIComponent(token)}&select=*`);const m=rows?.[0];if(!m)return res.status(404).send('Message not found');await event(m.id,'link_viewed',{user_agent:req.headers['user-agent']||''});const tenants=await supa(`tenants?id=eq.${m.tenant_id}&select=name`);const name=tenants?.[0]?.name||'Tenant';res.setHeader('Content-Type','text/html; charset=utf-8');return res.status(200).send(`<!doctype html><meta name="viewport" content="width=device-width"><title>${esc(m.subject)}</title><body style="margin:0;background:#f4f7fb;font-family:Arial,sans-serif;color:#17324f"><main style="max-width:680px;margin:40px auto;background:white;border:1px solid #dde6ef;border-radius:18px;padding:32px;box-shadow:0 18px 50px rgba(28,52,83,.08)"><div style="font-size:12px;font-weight:800;color:#1764be">MANAGERENT4U</div><h1 style="font-size:26px">${esc(m.subject||'Message')}</h1><p style="color:#61758d">For ${esc(name)}</p><div style="white-space:pre-wrap;line-height:1.7;font-size:15px">${esc(m.body)}</div><div style="margin-top:28px;padding-top:18px;border-top:1px solid #edf1f5;color:#8190a1;font-size:12px">This secure page records that the message link was viewed.</div></main></body>`)}catch(e){return res.status(500).send(esc(e.message||e))}
  }
  return res.status(400).json({error:'Invalid tracking mode'});
};

return module.exports; })();

module.exports = async (req,res) => {
  res.setHeader('Access-Control-Allow-Origin','*');
  res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');
  res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization');
  if(req.method==='OPTIONS') return res.status(204).end();
  const action = String(req.query.action || '').trim();
  const h = handlers[action];
  if(!h) return res.status(404).json({error:'Unknown messages action'});
  return h(req,res);
};
